export * from './balance.service';
import { BalanceService } from './balance.service';
export * from './banner.service';
import { BannerService } from './banner.service';
export * from './bonus.service';
import { BonusService } from './bonus.service';
export * from './globalization.service';
import { GlobalizationService } from './globalization.service';
export * from './loyalty.service';
import { LoyaltyService } from './loyalty.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './player.service';
import { PlayerService } from './player.service';
export * from './prodGame.service';
import { ProdGameService } from './prodGame.service';
export * from './promotion.service';
import { PromotionService } from './promotion.service';
export * from './reward.service';
import { RewardService } from './reward.service';
export * from './sportsbook.service';
import { SportsbookService } from './sportsbook.service';
export * from './template.service';
import { TemplateService } from './template.service';
export const APIS = [BalanceService, BannerService, BonusService, GlobalizationService, LoyaltyService, MessageService, PaymentService, PlayerService, ProdGameService, PromotionService, RewardService, SportsbookService, TemplateService];
