/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GetBalanceResponse } from '../model/getBalanceResponse';
// @ts-ignore
import { GetPlayerTransactionsRequest } from '../model/getPlayerTransactionsRequest';
// @ts-ignore
import { GetPlayerTransactionsResponse } from '../model/getPlayerTransactionsResponse';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';
// @ts-ignore
import { TransactionDetailsRequest } from '../model/transactionDetailsRequest';
// @ts-ignore
import { TransactionDetailsResponse } from '../model/transactionDetailsResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class BalanceService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get player balance
     * # Get balance  The method returns the players balance for multiple wallets.    # Errors    Error code                    | Description  ----------------------------  | -----------  &#x60;PlayerSessionCheckFailed&#x60;    | Checking player session failed.  &#x60;PlayerNotFound&#x60;              | Player not found.  &#x60;InternalError&#x60;               | Internal error.
     * @endpoint get /api/portal/v1/balance
     * @param includeBonusProductType Include bonus per product type in response.
     * @param includeBonusType Include bonus type in response.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1BalanceGet(includeBonusProductType?: string, includeBonusType?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetBalanceResponse>;
    public apiPortalV1BalanceGet(includeBonusProductType?: string, includeBonusType?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetBalanceResponse>>;
    public apiPortalV1BalanceGet(includeBonusProductType?: string, includeBonusType?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetBalanceResponse>>;
    public apiPortalV1BalanceGet(includeBonusProductType?: string, includeBonusType?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeBonusProductType, 'IncludeBonusProductType');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeBonusType, 'IncludeBonusType');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/balance`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetBalanceResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Transaction details
     * # Transaction details                Returns transaction details information                # Errors                Error code                  | Description  --------------------------- | -----------  &#x60;InternalError &#x60;            | Internal error.
     * @endpoint post /api/portal/v1/balance/transaction-details
     * @param transactionDetailsRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1BalanceTransactionDetailsPost(transactionDetailsRequest?: TransactionDetailsRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TransactionDetailsResponse>;
    public apiPortalV1BalanceTransactionDetailsPost(transactionDetailsRequest?: TransactionDetailsRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TransactionDetailsResponse>>;
    public apiPortalV1BalanceTransactionDetailsPost(transactionDetailsRequest?: TransactionDetailsRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TransactionDetailsResponse>>;
    public apiPortalV1BalanceTransactionDetailsPost(transactionDetailsRequest?: TransactionDetailsRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/balance/transaction-details`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TransactionDetailsResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: transactionDetailsRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Call provides all player transactions in provided date.
     * # Player transaction  Call provides all player transactions in provided date.    # Errors    Error code                    | Description  ----------------------------  | -----------  &#x60;PlayerSessionCheckFailed&#x60;    | Checking player session failed.  &#x60;InternalError&#x60;               | Internal error.
     * @endpoint post /api/portal/v1/balance/transactions
     * @param getPlayerTransactionsRequest Transaction request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1BalanceTransactionsPost(getPlayerTransactionsRequest?: GetPlayerTransactionsRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetPlayerTransactionsResponse>;
    public apiPortalV1BalanceTransactionsPost(getPlayerTransactionsRequest?: GetPlayerTransactionsRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetPlayerTransactionsResponse>>;
    public apiPortalV1BalanceTransactionsPost(getPlayerTransactionsRequest?: GetPlayerTransactionsRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetPlayerTransactionsResponse>>;
    public apiPortalV1BalanceTransactionsPost(getPlayerTransactionsRequest?: GetPlayerTransactionsRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/balance/transactions`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetPlayerTransactionsResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: getPlayerTransactionsRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
