/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ContentData } from '../model/contentData';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class BannerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get banners
     * # Get banners  The method will return list of banners.  # Errors                Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/cms/banners
     * @param slugs Category key list
     * @param portalId Portal ID
     * @param languageCode Language code
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1CmsBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ContentData>>;
    public apiPortalV1CmsBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ContentData>>>;
    public apiPortalV1CmsBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ContentData>>>;
    public apiPortalV1CmsBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (slugs === null || slugs === undefined) {
            throw new Error('Required parameter slugs was null or undefined when calling apiPortalV1CmsBannersGet.');
        }
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1CmsBannersGet.');
        }
        if (languageCode === null || languageCode === undefined) {
            throw new Error('Required parameter languageCode was null or undefined when calling apiPortalV1CmsBannersGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (slugs) {
            slugs.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'Slugs');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>languageCode, 'LanguageCode');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/cms/banners`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ContentData>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get player banners
     * # Get banners  The method will return list of banners.  # Errors                Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/cms/player/banners
     * @param slugs Category key list
     * @param portalId Portal ID
     * @param languageCode Language code
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1CmsPlayerBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ContentData>>;
    public apiPortalV1CmsPlayerBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ContentData>>>;
    public apiPortalV1CmsPlayerBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ContentData>>>;
    public apiPortalV1CmsPlayerBannersGet(slugs: Array<string>, portalId: number, languageCode: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (slugs === null || slugs === undefined) {
            throw new Error('Required parameter slugs was null or undefined when calling apiPortalV1CmsPlayerBannersGet.');
        }
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1CmsPlayerBannersGet.');
        }
        if (languageCode === null || languageCode === undefined) {
            throw new Error('Required parameter languageCode was null or undefined when calling apiPortalV1CmsPlayerBannersGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (slugs) {
            slugs.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'Slugs');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>languageCode, 'LanguageCode');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/cms/player/banners`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ContentData>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
