/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { LoyaltyDetailsResponse } from '../model/loyaltyDetailsResponse';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';
// @ts-ignore
import { RedeemLoyaltyPointsRequest } from '../model/redeemLoyaltyPointsRequest';
// @ts-ignore
import { RedeemedPointsTransactionsResponse } from '../model/redeemedPointsTransactionsResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class LoyaltyService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Loyalty detail
     * # Loyalty details    The method returns all players loyalty details.    # Errors      Error code                  | Description  --------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/loyalty
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1LoyaltyGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LoyaltyDetailsResponse>;
    public apiPortalV1LoyaltyGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LoyaltyDetailsResponse>>;
    public apiPortalV1LoyaltyGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LoyaltyDetailsResponse>>;
    public apiPortalV1LoyaltyGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/loyalty`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LoyaltyDetailsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Points transactions redeemed
     * # Redeem points transactions    The method returns the history of players\&#39; loyalty transactions (redeemed market points).        # Errors      Error code                          | Description  ----------------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;          | Checking player session failed.  &#x60;InternalError&#x60;                     | Internal error.
     * @endpoint get /api/portal/v1/loyalty/points
     * @param pageNumber Number of the page
     * @param pageSize Page size for the number of records per page.
     * @param dateFrom Start date for redeemed points transactions.
     * @param dateTo End date for redeemed points transactions.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1LoyaltyPointsGet(pageNumber: number, pageSize: number, dateFrom?: string, dateTo?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<RedeemedPointsTransactionsResponse>;
    public apiPortalV1LoyaltyPointsGet(pageNumber: number, pageSize: number, dateFrom?: string, dateTo?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<RedeemedPointsTransactionsResponse>>;
    public apiPortalV1LoyaltyPointsGet(pageNumber: number, pageSize: number, dateFrom?: string, dateTo?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<RedeemedPointsTransactionsResponse>>;
    public apiPortalV1LoyaltyPointsGet(pageNumber: number, pageSize: number, dateFrom?: string, dateTo?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (pageNumber === null || pageNumber === undefined) {
            throw new Error('Required parameter pageNumber was null or undefined when calling apiPortalV1LoyaltyPointsGet.');
        }
        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling apiPortalV1LoyaltyPointsGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageNumber, 'PageNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'PageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>dateFrom, 'DateFrom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>dateTo, 'DateTo');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/loyalty/points`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<RedeemedPointsTransactionsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Redeem Loyalty Points
     * # Redeem loyalty points    The method redeems loyalty points for player.     # Errors      Error code                          | Description  ----------------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;          | Checking player session failed.  &#x60;InternalError&#x60;                     | Internal error.  &#x60;PointsLessThanZero &#x60;               | Loyalty points less than zero.  &#x60;NotEnoughPoints&#x60;                   | Not enough points to redeem.  &#x60;BlockedRedemption&#x60;                 | Player blocked for redeeming points.  &#x60;RedeemLoyaltyPointsLimitExceeded&#x60;  | Points redemption limit exceeded.
     * @endpoint post /api/portal/v1/loyalty/points
     * @param redeemLoyaltyPointsRequest Redeem loyalty points request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1LoyaltyPointsPost(redeemLoyaltyPointsRequest?: RedeemLoyaltyPointsRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public apiPortalV1LoyaltyPointsPost(redeemLoyaltyPointsRequest?: RedeemLoyaltyPointsRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public apiPortalV1LoyaltyPointsPost(redeemLoyaltyPointsRequest?: RedeemLoyaltyPointsRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public apiPortalV1LoyaltyPointsPost(redeemLoyaltyPointsRequest?: RedeemLoyaltyPointsRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/loyalty/points`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: redeemLoyaltyPointsRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
