/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EnumGameIdResponse } from '../model/enumGameIdResponse';
// @ts-ignore
import { GameCategoriesResponse } from '../model/gameCategoriesResponse';
// @ts-ignore
import { GameCategoryTypesResponse } from '../model/gameCategoryTypesResponse';
// @ts-ignore
import { GameCycleStatusEnum } from '../model/gameCycleStatusEnum';
// @ts-ignore
import { GameMainTranslation } from '../model/gameMainTranslation';
// @ts-ignore
import { GameNotSecureRequest } from '../model/gameNotSecureRequest';
// @ts-ignore
import { GetGameHistoryResponse } from '../model/getGameHistoryResponse';
// @ts-ignore
import { GetGameMainsResponse } from '../model/getGameMainsResponse';
// @ts-ignore
import { GetGameParametersResponse } from '../model/getGameParametersResponse';
// @ts-ignore
import { GetGeneralLobbyForProductRequestATL } from '../model/getGeneralLobbyForProductRequestATL';
// @ts-ignore
import { GetGeneralLobbyForProductResponseATL } from '../model/getGeneralLobbyForProductResponseATL';
// @ts-ignore
import { GetPreGameMessagesResponse } from '../model/getPreGameMessagesResponse';
// @ts-ignore
import { GetRestrictionsResponse } from '../model/getRestrictionsResponse';
// @ts-ignore
import { LevelDataGameMain } from '../model/levelDataGameMain';
// @ts-ignore
import { PlayerGameRequest } from '../model/playerGameRequest';
// @ts-ignore
import { PlayerShortcutGameMainsResponse } from '../model/playerShortcutGameMainsResponse';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';
// @ts-ignore
import { PostGameResponse } from '../model/postGameResponse';
// @ts-ignore
import { TopRecentGame } from '../model/topRecentGame';
// @ts-ignore
import { TopWinnersATL } from '../model/topWinnersATL';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ProdGameService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Delete the game from the player shortcut
     * # Delete shortcut for a games     This method deletes the player\&#39;s existing games shortcut according to the entered external ID.    # Errors      Error code                 | Description  -------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60; | Checking player session failed.     &#x60;GameNotFound&#x60;             | Game with id {ExtGameId} does not exists.  &#x60;InternalError&#x60;            | Internal error
     * @endpoint delete /api/portal/v1/prod-game/favorite/{ExtGameId}
     * @param extGameId External game ID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameFavoriteExtGameIdDelete(extGameId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public apiPortalV1ProdGameFavoriteExtGameIdDelete(extGameId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public apiPortalV1ProdGameFavoriteExtGameIdDelete(extGameId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public apiPortalV1ProdGameFavoriteExtGameIdDelete(extGameId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (extGameId === null || extGameId === undefined) {
            throw new Error('Required parameter extGameId was null or undefined when calling apiPortalV1ProdGameFavoriteExtGameIdDelete.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/favorite/${this.configuration.encodeParam({name: "extGameId", value: extGameId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Adds a game shortcut to a player
     * # Add shortcut for a games     The method adds a new game shortcut to a player according to the entered external identifier.     # Errors      Error code                 | Description  -------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60; | Checking player session failed.     &#x60;GameNotFound&#x60;             | Game with id {ExtGameId} does not exists.  &#x60;InternalError&#x60;            | Internal error
     * @endpoint put /api/portal/v1/prod-game/favorite/{ExtGameId}
     * @param extGameId External game ID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameFavoriteExtGameIdPut(extGameId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public apiPortalV1ProdGameFavoriteExtGameIdPut(extGameId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public apiPortalV1ProdGameFavoriteExtGameIdPut(extGameId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public apiPortalV1ProdGameFavoriteExtGameIdPut(extGameId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (extGameId === null || extGameId === undefined) {
            throw new Error('Required parameter extGameId was null or undefined when calling apiPortalV1ProdGameFavoriteExtGameIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/favorite/${this.configuration.encodeParam({name: "extGameId", value: extGameId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Player Shortcut Game
     * # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PortalNotActive&#x60;           | Portal is not active.  &#x60;PortalNotExist&#x60;            | Portal does not exist.  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/prod-game/favorites/{PortalId}
     * @param portalId Portal Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameFavoritesPortalIdGet(portalId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlayerShortcutGameMainsResponse>;
    public apiPortalV1ProdGameFavoritesPortalIdGet(portalId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlayerShortcutGameMainsResponse>>;
    public apiPortalV1ProdGameFavoritesPortalIdGet(portalId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlayerShortcutGameMainsResponse>>;
    public apiPortalV1ProdGameFavoritesPortalIdGet(portalId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameFavoritesPortalIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/favorites/${this.configuration.encodeParam({name: "portalId", value: portalId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlayerShortcutGameMainsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns game categories for given portal
     * @endpoint get /api/portal/v1/prod-game/game-categories/{PortalId}
     * @param portalId Portal ID in which the player will login.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGameCategoriesPortalIdGet(portalId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GameCategoriesResponse>;
    public apiPortalV1ProdGameGameCategoriesPortalIdGet(portalId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GameCategoriesResponse>>;
    public apiPortalV1ProdGameGameCategoriesPortalIdGet(portalId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GameCategoriesResponse>>;
    public apiPortalV1ProdGameGameCategoriesPortalIdGet(portalId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameGameCategoriesPortalIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game-categories/${this.configuration.encodeParam({name: "portalId", value: portalId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GameCategoriesResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns game categories types
     * @endpoint get /api/portal/v1/prod-game/game-category-types
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGameCategoryTypesGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GameCategoryTypesResponse>;
    public apiPortalV1ProdGameGameCategoryTypesGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GameCategoryTypesResponse>>;
    public apiPortalV1ProdGameGameCategoryTypesGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GameCategoryTypesResponse>>;
    public apiPortalV1ProdGameGameCategoryTypesGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game-category-types`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GameCategoryTypesResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Basic game information, translated to the provided language code
     * # Get game help    This method returns basic information about a specific game.  The information is structured in key value pairs. The value is already translated  into the specified language and can be displayed in the client.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/prod-game/game/help
     * @param extGameId External game id
     * @param portalId Portal Id
     * @param languageCode Language code    The language code controls which translation is returned
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGameHelpGet(extGameId: string, portalId: number, languageCode: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<GameMainTranslation>>;
    public apiPortalV1ProdGameGameHelpGet(extGameId: string, portalId: number, languageCode: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<GameMainTranslation>>>;
    public apiPortalV1ProdGameGameHelpGet(extGameId: string, portalId: number, languageCode: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<GameMainTranslation>>>;
    public apiPortalV1ProdGameGameHelpGet(extGameId: string, portalId: number, languageCode: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (extGameId === null || extGameId === undefined) {
            throw new Error('Required parameter extGameId was null or undefined when calling apiPortalV1ProdGameGameHelpGet.');
        }
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameGameHelpGet.');
        }
        if (languageCode === null || languageCode === undefined) {
            throw new Error('Required parameter languageCode was null or undefined when calling apiPortalV1ProdGameGameHelpGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>extGameId, 'extGameId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'portalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>languageCode, 'languageCode');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game/help`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<GameMainTranslation>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get game parameters
     * # Get game parameters    Retrieves a list of parameters for a specific game    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/prod-game/game/parameters/{extGameId}
     * @param extGameId External game id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGameParametersExtGameIdGet(extGameId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetGameParametersResponse>;
    public apiPortalV1ProdGameGameParametersExtGameIdGet(extGameId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetGameParametersResponse>>;
    public apiPortalV1ProdGameGameParametersExtGameIdGet(extGameId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetGameParametersResponse>>;
    public apiPortalV1ProdGameGameParametersExtGameIdGet(extGameId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (extGameId === null || extGameId === undefined) {
            throw new Error('Required parameter extGameId was null or undefined when calling apiPortalV1ProdGameGameParametersExtGameIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game/parameters/${this.configuration.encodeParam({name: "extGameId", value: extGameId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetGameParametersResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns Game data for game launch (demo play)
     * # GetGameReturn    Free-play option for returning Launch game URL for the selected external game id. This allows non-registered (not logged in players) to launch a game.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;GameNotFound&#x60;              | Game with id {Id} does not exists  &#x60;InternalError&#x60;             | Internal error
     * @endpoint post /api/portal/v1/prod-game/game
     * @param gameNotSecureRequest Game Not Secure Request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGamePost(gameNotSecureRequest?: GameNotSecureRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PostGameResponse>;
    public apiPortalV1ProdGameGamePost(gameNotSecureRequest?: GameNotSecureRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PostGameResponse>>;
    public apiPortalV1ProdGameGamePost(gameNotSecureRequest?: GameNotSecureRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PostGameResponse>>;
    public apiPortalV1ProdGameGamePost(gameNotSecureRequest?: GameNotSecureRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PostGameResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: gameNotSecureRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get restrictions unsecure
     * # Get restrictions unsecure      This method returns restrictions/availability information. It includes data for the portal, product and product supplier.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;Internal error&#x60;            | Internal error.
     * @endpoint get /api/portal/v1/prod-game/game-restrictions
     * @param portalId Portal Id
     * @param countryCode Country Code
     * @param currencyCode Currency code
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGameRestrictionsGet(portalId: number, countryCode?: string, currencyCode?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetRestrictionsResponse>;
    public apiPortalV1ProdGameGameRestrictionsGet(portalId: number, countryCode?: string, currencyCode?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetRestrictionsResponse>>;
    public apiPortalV1ProdGameGameRestrictionsGet(portalId: number, countryCode?: string, currencyCode?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetRestrictionsResponse>>;
    public apiPortalV1ProdGameGameRestrictionsGet(portalId: number, countryCode?: string, currencyCode?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameGameRestrictionsGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>countryCode, 'CountryCode');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>currencyCode, 'CurrencyCode');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/game-restrictions`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetRestrictionsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns games in a specific category
     * # Get games by category    The method gives a list of game IDs in a specific category.    # Errors      Error code        | Description  ----------------- | ----------------------  &#x60;PortalNotExist&#x60;  | Portal does not exist.  &#x60;InternalError&#x60;   | Internal error
     * @endpoint get /api/portal/v1/prod-game/games/for-category/{CategoryId}
     * @param categoryId Category ID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGamesForCategoryCategoryIdGet(categoryId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<EnumGameIdResponse>;
    public apiPortalV1ProdGameGamesForCategoryCategoryIdGet(categoryId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EnumGameIdResponse>>;
    public apiPortalV1ProdGameGamesForCategoryCategoryIdGet(categoryId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EnumGameIdResponse>>;
    public apiPortalV1ProdGameGamesForCategoryCategoryIdGet(categoryId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (categoryId === null || categoryId === undefined) {
            throw new Error('Required parameter categoryId was null or undefined when calling apiPortalV1ProdGameGamesForCategoryCategoryIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/games/for-category/${this.configuration.encodeParam({name: "categoryId", value: categoryId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EnumGameIdResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get game history
     * # Get game history    Game history functionality provides the history of game results.   Each game (which requires integration with 3rd party game supplier) provides details screens where players can see the details of the specific game.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  \&#39;PlayerNotFound\&#39;            | Player not found.  \&#39;InternalError\&#39;             | Internal error.
     * @endpoint get /api/portal/v1/prod-game/games/history
     * @param fromDate Date from for players game history in ISO format (YYYY-MM-DD HH:MM:SS).
     * @param toDate Date to for players game history in ISO format (YYYY-MM-DD HH:MM:SS).
     * @param pageSize Page size for number of records per page.
     * @param pageNumber Page number.
     * @param status Status search criteria.
     * @param productType This will be predefined and PortalGateway consumers should get this from us.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGamesHistoryGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: GameCycleStatusEnum, productType?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetGameHistoryResponse>;
    public apiPortalV1ProdGameGamesHistoryGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: GameCycleStatusEnum, productType?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetGameHistoryResponse>>;
    public apiPortalV1ProdGameGamesHistoryGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: GameCycleStatusEnum, productType?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetGameHistoryResponse>>;
    public apiPortalV1ProdGameGamesHistoryGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: GameCycleStatusEnum, productType?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fromDate, 'FromDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>toDate, 'ToDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'PageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageNumber, 'PageNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>status, 'Status');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>productType, 'ProductType');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/games/history`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetGameHistoryResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the games for a specific portal
     * Warning: This method returns a large quantity of data and might cause your browser to lag.                # Errors      Error code                  | Description  --------------------------- | -----------  &#x60;PortalNotActive&#x60;           | Portal is not active.  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/prod-game/games/{PortalId}
     * @param portalId ID of the application / portal
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameGamesPortalIdGet(portalId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetGameMainsResponse>;
    public apiPortalV1ProdGameGamesPortalIdGet(portalId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetGameMainsResponse>>;
    public apiPortalV1ProdGameGamesPortalIdGet(portalId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetGameMainsResponse>>;
    public apiPortalV1ProdGameGamesPortalIdGet(portalId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameGamesPortalIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/games/${this.configuration.encodeParam({name: "portalId", value: portalId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetGameMainsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get General Lobby For Product Not Secure
     * # Lobby URL     Returns the url for general lobby of the product.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PluginNotFound&#x60;            | ProdGameManagement plug-in not found  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;InternalError&#x60;             | Internal error  &#x60;UnexpectedError&#x60;           | Unexpected error  &#x60;ExternalSystemError&#x60;       | Error occurred while trying to execute an action on external system
     * @endpoint post /api/portal/v1/prod-game/lobby-for-product
     * @param getGeneralLobbyForProductRequestATL Get General Lobby For Product Request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetGeneralLobbyForProductResponseATL>;
    public apiPortalV1ProdGameLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetGeneralLobbyForProductResponseATL>>;
    public apiPortalV1ProdGameLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetGeneralLobbyForProductResponseATL>>;
    public apiPortalV1ProdGameLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/lobby-for-product`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetGeneralLobbyForProductResponseATL>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: getGeneralLobbyForProductRequestATL,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns entire lobby games hierarchies (structure).
     * # Get Lobby (not secure)    The method will retrieve entire lobby games hierarchies (structure) for unauthenticated player.     # Errors      Error code                 | Description  -------------------------- | -----------  &#x60;PortalNotActive&#x60;          | Portal is not active.    &#x60;PortalNotExist&#x60;           | Portal does not exist.  &#x60;InvalidLevel&#x60;             | Level not found or restricted.   &#x60;InternalError&#x60;            | Internal error
     * @endpoint get /api/portal/v1/prod-game/lobby
     * @param portalId ID of  the application / portal.   See &#x60;GetPortals&#x60; for list of supported locales.
     * @param language Language code or culture code of player lobby game.
     * @param levelId Level ID that is used to further filter the returned list of categories.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<LevelDataGameMain>>;
    public apiPortalV1ProdGameLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<LevelDataGameMain>>>;
    public apiPortalV1ProdGameLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<LevelDataGameMain>>>;
    public apiPortalV1ProdGameLobbyGet(portalId: number, language?: string, levelId?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameLobbyGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>language, 'Language');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>levelId, 'LevelId');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/lobby`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<LevelDataGameMain>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns data required for launching a specific game for a player
     * # Post player game    The method returns data required for launching a specific game for the authenticated player.     # Errors      Error code                  | Description  --------------------------- | ----------------------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;InternalError&#x60;             | Internal error.  &#x60;GameNotFound&#x60;              | Game does not exists.  &#x60;GameNotAllowed&#x60;            | Game launch not allowed, cause of Player account.      &#x60;GameRestricted&#x60;            | Game is restricted.
     * @endpoint post /api/portal/v1/prod-game/player/game
     * @param playerGameRequest Player game request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGamePlayerGamePost(playerGameRequest?: PlayerGameRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PostGameResponse>;
    public apiPortalV1ProdGamePlayerGamePost(playerGameRequest?: PlayerGameRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PostGameResponse>>;
    public apiPortalV1ProdGamePlayerGamePost(playerGameRequest?: PlayerGameRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PostGameResponse>>;
    public apiPortalV1ProdGamePlayerGamePost(playerGameRequest?: PlayerGameRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/player/game`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PostGameResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: playerGameRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get restrictions for player
     * # Get restrictions for player    Returns restriction/availability data, similar to GetRestrictionsNotSecure.  However this method returns data in regards to the player.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;Internal error&#x60;            | Internal error.
     * @endpoint get /api/portal/v1/prod-game/player/game-restrictions
     * @param portalId Portal id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGamePlayerGameRestrictionsGet(portalId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetRestrictionsResponse>;
    public apiPortalV1ProdGamePlayerGameRestrictionsGet(portalId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetRestrictionsResponse>>;
    public apiPortalV1ProdGamePlayerGameRestrictionsGet(portalId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetRestrictionsResponse>>;
    public apiPortalV1ProdGamePlayerGameRestrictionsGet(portalId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGamePlayerGameRestrictionsGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/player/game-restrictions`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetRestrictionsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get General Lobby For Product
     * # Lobby URL     Returns the url for general lobby of the product.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PluginNotFound&#x60;            | ProdGameManagement plug-in not found  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;InternalError&#x60;             | Internal error  &#x60;UnexpectedError&#x60;           | Unexpected error  &#x60;ExternalSystemError&#x60;       | Error occurred while trying to execute an action on external system
     * @endpoint post /api/portal/v1/prod-game/player/lobby-for-product
     * @param getGeneralLobbyForProductRequestATL Get General Lobby For Product Request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGamePlayerLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetGeneralLobbyForProductResponseATL>;
    public apiPortalV1ProdGamePlayerLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetGeneralLobbyForProductResponseATL>>;
    public apiPortalV1ProdGamePlayerLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetGeneralLobbyForProductResponseATL>>;
    public apiPortalV1ProdGamePlayerLobbyForProductPost(getGeneralLobbyForProductRequestATL?: GetGeneralLobbyForProductRequestATL, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/player/lobby-for-product`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetGeneralLobbyForProductResponseATL>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: getGeneralLobbyForProductRequestATL,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of categories for a certain level.
     * # Get Player lobby    The method will retrieve a list of categories for a certain level.   Each category can contain several sub-categories (tree structure) as well as a list of games.     # Errors      Error code                 | Description  -------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60; | Checking player session failed.     &#x60;PortalNotActive&#x60;          | Portal is not active.    &#x60;PortalNotExist&#x60;           | Portal does not exist.  &#x60;InvalidLevel&#x60;             | Level not found or restricted.   &#x60;InternalError&#x60;            | Internal error
     * @endpoint get /api/portal/v1/prod-game/player/lobby
     * @param portalId ID of  the application / portal.   See &#x60;GetPortals&#x60; for list of supported locales.
     * @param language Language code or culture code of player lobby game.
     * @param levelId Level ID that is used to further filter the returned list of categories.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGamePlayerLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<LevelDataGameMain>>;
    public apiPortalV1ProdGamePlayerLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<LevelDataGameMain>>>;
    public apiPortalV1ProdGamePlayerLobbyGet(portalId: number, language?: string, levelId?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<LevelDataGameMain>>>;
    public apiPortalV1ProdGamePlayerLobbyGet(portalId: number, language?: string, levelId?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGamePlayerLobbyGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>language, 'Language');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>levelId, 'LevelId');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/player/lobby`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<LevelDataGameMain>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the pregame message for a player
     * # Get the pregame by external game id     This method returns the pregame message for a player.    To get the message on preLaunchGame following configuration steps need to be made:  * Configure bonus where only a subset of games(e.g.only Habanero games) contribute toward wagering requirements   * Launch a game that does not contribute towards wagering requirements.  * The following notification due to the pregame launch check is shown before the game is launched    # Errors      Error code              | Description  ----------------------- | ----------------------------  &#x60;PortalNotExist&#x60;        | Portal does not exist.  &#x60;InternalError&#x60;         | Internal error.  &#x60;GameNotFound&#x60;          | Game with id {extGameId} does not exists.  &#x60;GameNotAllowed&#x60;        | Game launch not allowed, cause of Player account.  &#x60;MissingMandatoryField&#x60; | Missing mandatory request parameter.
     * @endpoint get /api/portal/v1/prod-game/pre-game/{extGameId}
     * @param extGameId External game ID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGamePreGameExtGameIdGet(extGameId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetPreGameMessagesResponse>;
    public apiPortalV1ProdGamePreGameExtGameIdGet(extGameId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetPreGameMessagesResponse>>;
    public apiPortalV1ProdGamePreGameExtGameIdGet(extGameId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetPreGameMessagesResponse>>;
    public apiPortalV1ProdGamePreGameExtGameIdGet(extGameId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (extGameId === null || extGameId === undefined) {
            throw new Error('Required parameter extGameId was null or undefined when calling apiPortalV1ProdGamePreGameExtGameIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/pre-game/${this.configuration.encodeParam({name: "extGameId", value: extGameId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetPreGameMessagesResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets players recently played games
     * # Get player recently played games      Returns a list of players top recently played games.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;PlayerNotFound&#x60;            | Player not found.  &#x60;Internal error&#x60;            | Internal error.
     * @endpoint get /api/portal/v1/prod-game/recent
     * @param count Number of top games to return
     * @param portalId Portal id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameRecentGet(count: number, portalId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<TopRecentGame>>;
    public apiPortalV1ProdGameRecentGet(count: number, portalId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<TopRecentGame>>>;
    public apiPortalV1ProdGameRecentGet(count: number, portalId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<TopRecentGame>>>;
    public apiPortalV1ProdGameRecentGet(count: number, portalId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (count === null || count === undefined) {
            throw new Error('Required parameter count was null or undefined when calling apiPortalV1ProdGameRecentGet.');
        }
        if (portalId === null || portalId === undefined) {
            throw new Error('Required parameter portalId was null or undefined when calling apiPortalV1ProdGameRecentGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>count, 'Count');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>portalId, 'PortalId');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/recent`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<TopRecentGame>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Top Winners
     * # Top Winners    Returns Top Winners.    # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error
     * @endpoint get /api/portal/v1/prod-game/top-winners
     * @param listTypeId List Type Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1ProdGameTopWinnersGet(listTypeId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<TopWinnersATL>>;
    public apiPortalV1ProdGameTopWinnersGet(listTypeId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<TopWinnersATL>>>;
    public apiPortalV1ProdGameTopWinnersGet(listTypeId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<TopWinnersATL>>>;
    public apiPortalV1ProdGameTopWinnersGet(listTypeId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (listTypeId === null || listTypeId === undefined) {
            throw new Error('Required parameter listTypeId was null or undefined when calling apiPortalV1ProdGameTopWinnersGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>listTypeId, 'ListTypeId');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/prod-game/top-winners`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<TopWinnersATL>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
