/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ClaimRewardBonusRequest } from '../model/claimRewardBonusRequest';
// @ts-ignore
import { ClaimRewardItemRequest } from '../model/claimRewardItemRequest';
// @ts-ignore
import { GetAllRewardsResponse } from '../model/getAllRewardsResponse';
// @ts-ignore
import { GetClaimableRewardsResponse } from '../model/getClaimableRewardsResponse';
// @ts-ignore
import { GetClaimedRewardsResponse } from '../model/getClaimedRewardsResponse';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class RewardService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get all rewards with status Active and ComingSoon
     * # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;InternalError&#x60;             | Internal error
     * @endpoint get /api/portal/v1/reward/all
     * @param brandId BrandId to get rewards for
     * @param language Language code to be used for reward friendly names and descriptions. If null, then each reward will use its default friendly name and description. If there is no default friendly name and description for a reward, then it will use reward name and empty description.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1RewardAllGet(brandId: number, language?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetAllRewardsResponse>;
    public apiPortalV1RewardAllGet(brandId: number, language?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetAllRewardsResponse>>;
    public apiPortalV1RewardAllGet(brandId: number, language?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetAllRewardsResponse>>;
    public apiPortalV1RewardAllGet(brandId: number, language?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling apiPortalV1RewardAllGet.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>brandId, 'BrandId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>language, 'Language');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/reward/all`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetAllRewardsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Claim a reward of type Bonus
     * # Errors    Error code                   | Description  ---------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;   | Checking player session failed  &#x60;Security&#x60;                   | Player Id and Secure Token mismatch  &#x60;InternalError&#x60;              | Internal error  &#x60;RewardNotFound&#x60;             | The reward with the specified RewardId was not found  &#x60;InvalidOperation&#x60;           | Method was called with wrong reward type  &#x60;RewardNotActive&#x60;            | Reward status is not Active  &#x60;RewardNotAvailable&#x60;         | Current datetime is not within configured available timespan for this reward  &#x60;RequiredPointsChanged&#x60;      | Required points in the request do not match required points configured for this reward  &#x60;PlayerNotEligibleForReward&#x60; | The player is not eligible for this reward  &#x60;InsufficientPoints&#x60;         | The player does not have enough points to claim this reward  &#x60;BonusNotInActiveStatus&#x60;     | The status of the bonus configured for this reward is not Active  &#x60;DisabledProductType&#x60;        | The product type of the bonus is disabled for this player  &#x60;BonusUnsuccessfullyAwarded&#x60; | The bonus was not successfully awarded to the player
     * @endpoint post /api/portal/v1/reward/claim-bonus
     * @param claimRewardBonusRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1RewardClaimBonusPost(claimRewardBonusRequest?: ClaimRewardBonusRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public apiPortalV1RewardClaimBonusPost(claimRewardBonusRequest?: ClaimRewardBonusRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public apiPortalV1RewardClaimBonusPost(claimRewardBonusRequest?: ClaimRewardBonusRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public apiPortalV1RewardClaimBonusPost(claimRewardBonusRequest?: ClaimRewardBonusRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/reward/claim-bonus`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: claimRewardBonusRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Claim a reward of type Item
     * # Errors    Error code                   | Description  ---------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;   | Checking player session failed  &#x60;Security&#x60;                   | Player Id and Secure Token mismatch  &#x60;InternalError&#x60;              | Internal error  &#x60;RewardNotFound&#x60;             | The reward with the specified RewardId was not found  &#x60;InvalidOperation&#x60;           | Method was called with the wrong reward type  &#x60;RewardNotActive&#x60;            | Reward status is not Active  &#x60;RewardNotAvailable&#x60;         | Current datetime is not within the configured available timespan for this reward  &#x60;RequiredPointsChanged&#x60;      | Required points in the request do not match required points configured for this reward  &#x60;PlayerNotEligibleForReward&#x60; | The player is not eligible for this reward  &#x60;InsufficientPoints&#x60;         | The player does not have enough points to claim this reward
     * @endpoint post /api/portal/v1/reward/claim-item
     * @param claimRewardItemRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1RewardClaimItemPost(claimRewardItemRequest?: ClaimRewardItemRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public apiPortalV1RewardClaimItemPost(claimRewardItemRequest?: ClaimRewardItemRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public apiPortalV1RewardClaimItemPost(claimRewardItemRequest?: ClaimRewardItemRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public apiPortalV1RewardClaimItemPost(claimRewardItemRequest?: ClaimRewardItemRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/reward/claim-item`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: claimRewardItemRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get rewards available to be claimed by the player
     * # Errors    Error code                        | Description  --------------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;        | Checking player session failed  &#x60;Security&#x60;                        | Player Id and Secure Token mismatch  &#x60;InternalError&#x60;                   | Internal error
     * @endpoint get /api/portal/v1/reward/claimable
     * @param language Language code to be used for reward friendly names and descriptions    If the parameter is null, then the reward\&#39;s default friendly name and description will be used.  If friendly name and description don\&#39;t exist in the specified language, then the default friendly name and description will be used.  If there is no default friendly name and description for a reward, then it will use reward\&#39;s name and empty description.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1RewardClaimableGet(language?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetClaimableRewardsResponse>;
    public apiPortalV1RewardClaimableGet(language?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetClaimableRewardsResponse>>;
    public apiPortalV1RewardClaimableGet(language?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetClaimableRewardsResponse>>;
    public apiPortalV1RewardClaimableGet(language?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>language, 'Language');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/reward/claimable`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetClaimableRewardsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get rewards that were claimed by the player
     * # Errors    Error code                  | Description  --------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed  &#x60;Security&#x60;                  | Player Id and Secure Token mismatch  &#x60;InternalError&#x60;             | Internal error
     * @endpoint get /api/portal/v1/reward/claimed
     * @param language Language code to be used for reward friendly names and descriptions. If null, then each reward will use its default friendly name and description. If there is no default friendly name and description for a reward, then it will use reward name and empty description.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1RewardClaimedGet(language?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetClaimedRewardsResponse>;
    public apiPortalV1RewardClaimedGet(language?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetClaimedRewardsResponse>>;
    public apiPortalV1RewardClaimedGet(language?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetClaimedRewardsResponse>>;
    public apiPortalV1RewardClaimedGet(language?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>language, 'Language');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/reward/claimed`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetClaimedRewardsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
