/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GetBetHistoryResponse } from '../model/getBetHistoryResponse';
// @ts-ignore
import { PortalGatewayErrorResponse } from '../model/portalGatewayErrorResponse';
// @ts-ignore
import { PortalGatewayValidationFailedResponse } from '../model/portalGatewayValidationFailedResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class SportsbookService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get bet history
     * # Get bet history  Game history functionality provides the history of sportsbook game results. Each game (requires the integration with 3rd party game supplier)   provides details screens where players can see the details of the specific game.      # Errors      Error code                  | Description  --------------------------- | -----------  &#x60;PlayerSessionCheckFailed&#x60;  | Checking player session failed.  &#x60;PlayerNotFound&#x60;            | Player not foun  &#x60;InternalError&#x60;             | Internal error.
     * @endpoint get /api/portal/v1/sportsbook/bets
     * @param fromDate Filter from date
     * @param toDate Filter to date
     * @param pageSize Number of entries on page
     * @param pageNumber Number of the page
     * @param status Status of bet history
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPortalV1SportsbookBetsGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetBetHistoryResponse>;
    public apiPortalV1SportsbookBetsGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetBetHistoryResponse>>;
    public apiPortalV1SportsbookBetsGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetBetHistoryResponse>>;
    public apiPortalV1SportsbookBetsGet(fromDate?: string, toDate?: string, pageSize?: number, pageNumber?: number, status?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fromDate, 'FromDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>toDate, 'ToDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'PageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageNumber, 'PageNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>status, 'Status');

        let localVarHeaders = this.defaultHeaders;

        // authentication (ApiKey_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('ApiKey_PG', 'X-API-Key', localVarHeaders);

        // authentication (JwtBearer_PG) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JwtBearer_PG', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/portal/v1/sportsbook/bets`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetBetHistoryResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
