# Stage 1: Development environment for Angular
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN rm -rf node_modules package-lock.json && npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "watch"]
