import { BreakpointObserver } from '@angular/cdk/layout';
import {
  AfterViewInit,
  Component,
  ElementRef,
  HostListener,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { GameCategoriesService } from '@app/@core/game-categories.service';
import { AppBreakpoints } from '@app/@shared';
import { GameProviderData, GameTile } from '@app/@shared/models';
import { I18nService } from '@app/i18n';
import { SwiperOptions } from 'swiper';
import { NavigationOptions } from 'swiper/types';

@Component({
  selector: 'app-games-tiles',
  templateUrl: './games.component.html',
  styleUrls: ['./games.component.scss'],
})
export class GameTilesComponent implements OnChanges, OnInit, AfterViewInit {
  @ViewChild('gameGridContainer', { static: true }) gameGridContainer!: ElementRef<HTMLElement>;
  @Input() initialLoadAmount = 10;
  @Input() gameCatalog = '';
  @Input() gameCatalogCleanName = '';
  @Input() selectedProviderList: GameProviderData[] = [];
  @Input() gamesList: GameTile[] | null = null;
  @Input() initialRows = 2; // how many rowst to show initially, 0 is for auto
  @Input() showOnlyInitialRows = true; // should list show only initialRows (no auto rows) ?
  @Input() set categoryId(categoryId: number | undefined) {
    this._categoryId = categoryId;

    this.swiperConfig.navigation = {
      nextEl: `.games-swiper-navigation-right-${categoryId}`,
      prevEl: `.games-swiper-navigation-left-${categoryId}`,
      enabled: true,
    } as NavigationOptions;
    this.swiperConfig = { ...this.swiperConfig };
  }

  get categoryId(): number | undefined {
    return this._categoryId;
  }

  private _categoryId?: number;

  gamesDisplayed: GameTile[] | null = null;
  allGamesCount = 0;

  endOfGames = true;
  hasHiddenRows = false;

  // css string to specify rows in grid layout (so we can do it without js)
  gridTemplateRows = '';
  // local variable to show/hide autogenerated rows in grid layout
  // - this is how grid layout is used to preview only pre-defined number of rows
  //   without knowing/limiting the number of elements in the grid
  hideAutogeneratedRows = this.showOnlyInitialRows;

  swiperConfig: SwiperOptions = {
    slidesPerView: 6,
    spaceBetween: 8,
    slidesOffsetAfter: 8,
    navigation: {
      nextEl: `.games-swiper-navigation-right-${this.categoryId}`,
      prevEl: `.games-swiper-navigation-left-${this.categoryId}`,
      enabled: true,
    },
    scrollbar: { draggable: true },
  };

  constructor(
    private breakpointObserver: BreakpointObserver,
    private gameCategoriesService: GameCategoriesService,
    private i18nService: I18nService,
    private route: ActivatedRoute
  ) {
    this.breakpointObserver.observe(AppBreakpoints.LtSmall2).subscribe((value) => {
      this.swiperConfig.slidesPerView = value.matches ? 'auto' : 6;
      this.swiperConfig.spaceBetween = value.matches ? 7.5 : 22.36;

      this.swiperConfig = { ...this.swiperConfig };
    });
  }

  get gameCatalogTranslated() {
    return (
      this.gameCategoriesService.getCategoryTranslationById(this.categoryId ?? 0, this.i18nService.language) ??
      this.gameCatalog
    );
  }

  get isLive() {
    return this.route.snapshot.data?.['isLive'];
  }

  ngOnInit() {
    this.gridTemplateRows = `repeat(${this.initialRows}, 1fr)`;
    // check if initialRows is auto
    if (!this.initialRows) {
      this.hideAutogeneratedRows = false;
    }
  }

  ngAfterViewInit() {
    setTimeout(() => {
      this.checkForHiddenColumns();
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['selectedProviderList'] || changes['gamesList']) {
      this.endOfGames = true;
      this.prepareGames();
    }
  }

  // add a host listener to detect screen width change
  @HostListener('window:resize', ['$event'])
  onResize(event: Event): void {
    this.checkForHiddenColumns();
  }

  // TODO: [alesz] review this, looks like unnecessary complicated for the task
  loadMore(): void {
    this.hideAutogeneratedRows = false;
    // disabling autogenerated rows also makes hasHiddenRows obsolete
    this.hasHiddenRows = false;

    if (this.endOfGames || !this.gamesList || !this.gamesDisplayed) {
      return;
    }

    const lastGame = this.gamesDisplayed[this.gamesDisplayed.length - 1];

    if (this.initialLoadAmount) {
      if (lastGame) {
        const filteredGames = this.getFilteredGames();
        const indexOfLastElement = filteredGames.findIndex((game: GameTile) => {
          return game.externalGameId === lastGame.externalGameId && game.gameProviderId === lastGame.gameProviderId;
        });

        this.gamesDisplayed = filteredGames.slice(0, indexOfLastElement + this.initialLoadAmount + 1);

        if (filteredGames.length === this.gamesDisplayed.length) {
          this.endOfGames = true;
        }
      }
    }
  }

  prepareGames() {
    const filteredGames = this.getFilteredGames();
    this.gamesDisplayed = filteredGames.slice(0, this.initialLoadAmount) ?? null;
    this.endOfGames = filteredGames.length === this.gamesDisplayed.length;
    this.allGamesCount = filteredGames?.length ?? 0;
  }

  private checkForHiddenColumns() {
    /**
     * grid-template-rows will return something like that (row sizes, split by space):
     *   188.016px 188.016px
     * When there are hidden rows in the grid, return will be:
     *  188.016px 188.016px 0px 0px
     * where 0px is one hidden row
     *
     * Because of the way grid is configured, 0px will always identify hidden row with
     * some games - we can use this to trigger show more button in very efficient way.
     */
    if (this.hideAutogeneratedRows && this.gameGridContainer) {
      const gridCssRows = window
        .getComputedStyle(this.gameGridContainer.nativeElement)
        .getPropertyValue('grid-template-rows');
      //console.warn(`${this.gameCatalog} grid columns: ${gridCssColumns}`);
      this.hasHiddenRows = gridCssRows?.trim().endsWith('0px');
    } else {
      this.hasHiddenRows = false;
    }
  }

  // TODO: [alesz] review this, looks like unnecessary complicated for the task
  private getFilteredGames(): GameTile[] {
    if (!this.gamesList) return [];

    let filteredGames: GameTile[] = [];
    if (this.selectedProviderList.length !== 0) {
      filteredGames = this.gamesList.filter(
        (game) => game.gameProviderId && this.selectedProviderList.find((t) => t.id === game.gameProviderId)
      );
    } else {
      filteredGames = this.gamesList;
    }

    return filteredGames;
  }
}
