import { TransactionHistoryModel, TransactionStatusEnum, TransactionTypeEnum } from '@app/@shared/models';

export const TransactionHistoryMock: TransactionHistoryModel[] = [
  {
    id: '123j4h1k2j34',
    createTime: new Date().toLocaleString('pr-BR'),
    amount: 1000,
    amountResolved: '1000,00',
    balanceAfterResolved: '1000,00',
    balanceBefore: 0,
    balanceBeforeResolved: '0,00',
    status: TransactionStatusEnum.Completed,
    statusResolved: 'Completed',
    type: TransactionTypeEnum.Deposit,
    typeResolved: 'aaa',
    payMethod: 'CoinsPaid v2',
    balanceAfter: 1000,
    providerName: 'Pix',
  },
  {
    id: '123j4h1k2j34',
    createTime: new Date().toLocaleString('pr-BR'),
    amount: 1000,
    amountResolved: '1000,00',
    balanceAfterResolved: '1000,00',
    balanceBefore: 0,
    balanceBeforeResolved: '0,00',
    status: TransactionStatusEnum.Cancelled,
    statusResolved: 'Cancelled',
    type: TransactionTypeEnum.Withdrawal,
    typeResolved: 'Withdrawal',
    payMethod: 'CoinsPaid v2',
    balanceAfter: 1000,
    providerName: 'Pix',
  },
  {
    id: '123j4h1k2j34',
    createTime: new Date().toLocaleString('pr-BR'),
    amount: 55,
    amountResolved: '55,00',
    balanceAfterResolved: '110,00',
    balanceBefore: 55,
    balanceBeforeResolved: '55,00',
    status: TransactionStatusEnum.Completed,
    statusResolved: 'Completed',
    type: TransactionTypeEnum.Deposit,
    typeResolved: 'Deposit',
    payMethod: 'CoinsPaid v2',
    balanceAfter: 1000,
    providerName: 'Pix2',
  },
  {
    id: '123j4h1k2j34',
    createTime: new Date().toLocaleString('pr-BR'),
    amount: 1000,
    amountResolved: '1000,00',
    balanceAfterResolved: '1000,00',
    balanceBefore: 0,
    balanceBeforeResolved: '0,00',
    status: TransactionStatusEnum.Completed,
    statusResolved: 'Completed',
    type: TransactionTypeEnum.Deposit,
    typeResolved: 'Deposit',
    payMethod: 'CoinsPaid v2',
    balanceAfter: 1000,
    providerName: 'Pix',
  },
];
