// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

/**
 * base-environment*.ts files should not be used directly in the project, they are base environment variables
 * that needs to be extended in environemnt*.ts files:
 *   base-environment.ts      - for dev environments
 *   base-environment.prod.ts - for production environments
 */
export const baseEnvironment = {
  production: false,
  version: env['npm_package_version'] + '-dev',
  serverUrl: '',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'pt-BR'],
  desktopPortalId: 1,
  mobilePortalId: 2,
  defaultBrandId: 2,
  API_BASE_PATH: '',
  API_GEOLOCATION_PATH: 'https://ipapi.co/json/',
  useLocalHtmlTemplates: false, // Set this to true to use the local template definitions in `cms-templates-data`
  demoPlayEnabled: false,
  //indexPageTitle: '<started with no brand>', //currently not needed because there is only one brand
  indexPageTitle: 'BetAki | Apostas Regulamentadas, Super Odds e Diversão Garantida',

  // THIS IS OVERRIDEN BY THE CONFIGURATION LOADED IN RUNTIME from <root>/deploy-config.json
  deployConfig: {
    apiKey: '',
    gaTrackingCode: '', // Google analytics ID
    assetsBaseUrl: '',
    assetsPath: '',
    assetsQueryString: '',
    gamesThumbsBaseUrl: '',
    gamesThumbsUrlSuffix: '',
    antillephoneLicensingSealId: '',
    antillephoneLicensingScriptMethodId: '',
    antillephoneLicensingApgSealJsUrl: '',
    longVersion: '',
    gtmId: '', // Google Tag Manager ID
    fingerprintApiKey: '', //Fingerprint Api Key
    fingerprintEndpoint: '',
    affiliateDataExpiryOffset: 168,
    seoHostname: 'https://betaki.bet.br/',
    sportsbookIntegration: '',
    sportsbookSDK: '',
    cmsSlugPostfix: '',
    brandId: 2,
    desktopPortalId: 1,
    mobilePortalId: 2,
    brandName: '',
    socialInstagramUrl: 'https://www.instagram.com/betakioficial',
    socialTikTokUrl: 'https://www.tiktok.com/@betakioficial?_t=ZM-8tTSPMU6MMg&_r=1',
    socialTwitterUrl: 'https://x.com/oficialbetaki?s=11',
    defaultLanguage: 'pt-BR',
    tawkToSDK: '',
    legitimuzSDKToken: 'fce8adab-1411-45a1-a244-8e70d446a2b9',
    paymentTestModeEnabled: true,
  },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
