// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { baseEnvironment } from './base-environment';

/**
 * base-environment*.ts files should not be used directly in the project, they are base environment variables
 * that needs to be extended in environemnt*.ts files:
 *   base-environment.ts      - for dev environments
 *   base-environment.prod.ts - for production environments
 */
export const baseEnvironmentProd = Object.assign(baseEnvironment, {
  production: true,
  version: env['npm_package_version'],
});
