// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';

export const environment = {
  production: true,
  version: 1.0,
  serverUrl: '',
  defaultLanguage: 'pt-BR',
  supportedLanguages: ['en-US', 'pt-BR'],
  desktopPortalId: 5,
  mobilePortalId: 6,
  defaultBrandId: 2,
  API_BASE_PATH: '', // from environment.prod.ts
  useLocalHtmlTemplates: false, // Should be false for production
  demoPlayEnabled: false,
  indexPageTitle: 'Bet Aki | Apostas Regulamentadas, Super Odds e Diversão Garantida', // from environment-betaki.prod.ts

  deployConfig: {
    apiKey: 'e3d8ca29-c8a4-40c1-9246-94887777ed6a',
    gaTrackingCode: 'GTM-KSQFD799',
    assetsBaseUrl: '',
    assetsPath: '',
    assetsQueryString: '',
    gamesThumbsBaseUrl: 'https://pp-assets.icbkiassets.com/cmslibrary/bki/assets/general/gamethumbnails',
    gamesThumbsUrlSuffix: '',
    antillephoneLicensingSealId: '',
    antillephoneLicensingScriptMethodId: '',
    antillephoneLicensingApgSealJsUrl: '',
    longVersion: '',
    gtmId: 'GTM-KSQFD799',
    cmsSlugPostfix: 'betaki',
    brandId: 4,
    desktopPortalId: 5,
    mobilePortalId: 6,
    seoHostname: 'https://betaki.bet.br/',
    sportsbookIntegration: 'betaki',
    sportsbookSDK: 'https://sb2wsdk-altenar2-stage.biahosted.com/altenarWSDK.js',
    affiliateDataExpiryOffset: 168,
    brandName: 'Betaki',
    socialInstagramUrl: 'https://www.instagram.com/betakioficial',
    socialTikTokUrl: 'https://www.tiktok.com/@betakioficial?_t=ZM-8tTSPMU6MMg&_r=1',
    socialTwitterUrl: 'https://x.com/oficialbetaki?s=11',
    defaultLanguage: 'pt-BR',
    tawkToSDK: 'https://embed.tawk.to/665338ba981b6c564774d393/1huqhb6hp',
    legitimuzSDKToken: 'fce8adab-1411-45a1-a244-8e70d446a2b9',
    paymentTestModeEnabled: true,
  },
};
