// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';

/**
 * Where the app runs. Everything about *who* it runs as lives in `brands/<slug>/brand.config.ts`
 * and is reached through the `BRAND` token (see `src/app/@core/brand`).
 */
export const environment = {
  production: false,
  version: env['npm_package_version'] + '-dev',
  API_BASE_PATH: '',
  API_GEOLOCATION_PATH: 'https://ipapi.co/json/',
  useLocalHtmlTemplates: true, // Set this to true to use the local template definitions in `cms-templates-data`
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
