/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AccountTypeEnum = {
    FakeMoney: 'FakeMoney',
    Money: 'Money',
    BonusMoney: 'BonusMoney',
    LoyaltyPoints: 'LoyaltyPoints',
    RingfencedBalance: 'RingfencedBalance',
    PendingWinnings: 'PendingWinnings',
    ExternalBonus: 'ExternalBonus',
    NonWithdrawableBalance: 'NonWithdrawableBalance',
    WithdrawableBalance: 'WithdrawableBalance'
} as const;
export type AccountTypeEnum = typeof AccountTypeEnum[keyof typeof AccountTypeEnum];

