/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WagerTypeEnum } from './wagerTypeEnum';
import { WageringContributionModeEnum } from './wageringContributionModeEnum';
import { AccountTypeEnum } from './accountTypeEnum';
import { BonusCategoryIdEnum } from './bonusCategoryIdEnum';


export interface Account { 
    /**
     * Account name
     */
    name?: string | null;
    /**
     * Balance
     */
    balance?: number;
    /**
     * Real money locked amount.
     */
    lockedAmount?: number;
    /**
     * Currency
     */
    currency?: string | null;
    accountType?: AccountTypeEnum;
    /**
     * Product type for which bonus the balance is applicable.
     */
    productType?: string | null;
    /**
     * Wagering requuirement for active bonus.
     */
    wageringRequirement?: number | null;
    /**
     * Currenty wagered with active bonus.
     */
    wagered?: number | null;
    wagerType?: WagerTypeEnum;
    /**
     * Bonus type for which bonus the balance is applicable.
     */
    bonusType?: string | null;
    /**
     * Amount of money that was locked when the bonus was awarded.
     */
    initiallyLockedAmount?: number;
    bonusCategoryId?: BonusCategoryIdEnum;
    /**
     * Player bonus id (set only on account type BonusMoney)
     */
    playerBonusId?: number | null;
    wageringContributionMode?: WageringContributionModeEnum;
    /**
     * Number of required bonus wagering bets
     */
    numWageredRequirement?: number | null;
    /**
     * Number of successful bets already made at the bonus wagering
     */
    totalNumWagered?: number | null;
}
export namespace Account {
}


