/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentTypeEnum } from './paymentInstrumentTypeEnum';


/**
 * Get Payment Accounts Request
 */
export interface AddPaymentAccountRequest { 
    paymentInstrumentType?: PaymentInstrumentTypeEnum;
    /**
     * Payment instrument id: 22 – LocalBankTransfer(bank accounts)
     */
    paymentInstrumentId?: number | null;
    /**
     * ID of payment provider.
     */
    paymentProviderId?: number | null;
    /**
     * Additional payment account parameters.
     */
    parameters?: { [key: string]: string; } | null;
    /**
     * Send true for testing purposes.
     */
    testMode?: boolean;
}
export namespace AddPaymentAccountRequest {
}


