/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Annual verification for player via face auth
 */
export interface AnnualVerificationAuthRequest { 
    /**
     * Player ID.
     */
    id?: number;
    /**
     * Valid email address, 50 characters maximum.
     */
    eMail: string;
    /**
     * Mobile phone number.
     */
    mobilePhone: string;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    firstName: string;
    /**
     * Middle name, 2 characters minimum, 50 characters maximum.
     */
    middleName?: string | null;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    lastName: string;
    /**
     * City, 50 characters maximum.
     */
    city: string;
    /**
     * Post code. 50 characters maximum.
     */
    postalCode: string;
    /**
     * Street name. 130 characters maximum.
     */
    street: string;
    /**
     * House number. 30 characters maximum.
     */
    houseNumber: string;
    /**
     * State. 50 characters maximum.
     */
    state: string;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode: string;
}

