/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApprovalStatusEnum = {
    Unapproved: 'Unapproved',
    Approved: 'Approved',
    Partial: 'Partial',
    Declined: 'Declined'
} as const;
export type ApprovalStatusEnum = typeof ApprovalStatusEnum[keyof typeof ApprovalStatusEnum];

