/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GamesModel } from './gamesModel';


export interface AvailableFreeSpinGamesModel { 
    /**
     * iCore bonus configuration ID
     */
    bonusConfigurationId?: number | null;
    /**
     * External bonus configuration ID
     */
    bonusId?: number | null;
    /**
     * Bonus name in iCore configuration
     */
    bonusName?: string | null;
    /**
     * Bonus friendly name in iCore configuration
     */
    bonusFriendlyName?: string | null;
    /**
     * Player context bonus ID
     */
    playerBonusId?: number | null;
    /**
     * List of games
     */
    games?: Array<GamesModel> | null;
}

