/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Availability flags
 */
export interface AvailabilityFlags { 
    /**
     * If true internal players cannot use the product
     */
    internalPlayerRestricted?: boolean;
    /**
     * If true, external players cannot use the product
     */
    externalPlayerRestricted?: boolean;
    /**
     * If true, unknown players cannot use the product
     */
    unknownPlayerRestricted?: boolean;
    /**
     * If true, maintenance mode is enabled
     */
    maintenanceModeEnabled?: boolean;
    /**
     * If true, real play is restricted
     */
    realPlayRestricted?: boolean;
    /**
     * If true, demo play is restricted
     */
    demoPlayRestricted?: boolean;
}

