/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AwardConditionAwardTimeTypeEnum } from './awardConditionAwardTimeTypeEnum';
import { MinMaxAmountData } from './minMaxAmountData';
import { TimePeriodTypeEnum } from './timePeriodTypeEnum';


export interface AwardConditionFulfilmentData { 
    /**
     * Trigger type  Possible values:  * Deposit  * Wager  * Loss  * NewPaymentMethod  * Win  * ChangeOfVipLevel  * Transfer  * MarketingPoints  * Event
     */
    triggerType?: string | null;
    /**
     * Amount data (present only for trigger types where min and max values are defined)
     */
    amount?: Array<MinMaxAmountData> | null;
    /**
     * Treshold value to meet condition criteria (present only when min and max values are not defined)
     */
    thresholdValue?: number | null;
    /**
     * List of payment instrument ids for which condition is applicable (only present for Deposit and NewPaymentMethod trigger types)
     */
    paymentMethodIDs?: Array<number> | null;
    /**
     * List of VIP level ids for which condition is applicable (present only for ChangeOfVipLevel trigger type)
     */
    includedVIPlevelsIDs?: Array<number> | null;
    timePeriodType?: TimePeriodTypeEnum;
    /**
     * Player fulfillment total amount
     */
    playerFulfillmentTotal?: number | null;
    /**
     * Player fulfillment amount left to satisfy awarding condition
     */
    playerFulfillmentLeft?: number | null;
    /**
     * Player fulfillment unit
     */
    playerFulfillmentUnit?: string | null;
    /**
     * Award condition met flag
     */
    awardConditionMet?: boolean | null;
    /**
     * Current deposit number counter (present only for Deposit trigger type)
     */
    currentDepositNumber?: number | null;
    awardTimeType?: AwardConditionAwardTimeTypeEnum;
}
export namespace AwardConditionFulfilmentData {
}


