/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AwardConditionAwardTimeTypeEnum = {
    AtTheEndOfPeriod: 'AtTheEndOfPeriod',
    Immediately: 'Immediately'
} as const;
export type AwardConditionAwardTimeTypeEnum = typeof AwardConditionAwardTimeTypeEnum[keyof typeof AwardConditionAwardTimeTypeEnum];

