/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BonusOptInSchedulingData { 
    timeToActivatePendingBonus?: number | null;
    timeToRedeemActiveBonus?: number | null;
    timeToAcceptAwardedBonus?: number | null;
    timeToMeetConditionsForWaitingBonus?: number | null;
    timeToStartContributingToWR?: number | null;
    timeToUseFreeSpins?: number | null;
    bonusFixedExpiryDate?: string | null;
    bonusCurrentExpiryCondition?: string | null;
    bonusCurrentExpiryConditionDate?: string | null;
    expirationDateReal?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
}

