/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BonusIncentiveAwardConditionTypeReturnEnum = {
    Deposit: 'Deposit',
    Wager: 'Wager',
    Loss: 'Loss',
    NewPaymentMethod: 'NewPaymentMethod',
    Win: 'Win',
    ChangeOfVipLevel: 'ChangeOfVipLevel',
    Transfer: 'Transfer',
    MarketingPoints: 'MarketingPoints',
    Event: 'Event',
    Login: 'Login',
    P2PBuyIn: 'P2PBuyIn',
    P2PRakeFee: 'P2PRakeFee',
    WithdrawalRequest: 'WithdrawalRequest',
    TokenConversion: 'TokenConversion',
    UpgradeOfVipLevel: 'UpgradeOfVipLevel',
    BonusPoints: 'BonusPoints'
} as const;
export type BonusIncentiveAwardConditionTypeReturnEnum = typeof BonusIncentiveAwardConditionTypeReturnEnum[keyof typeof BonusIncentiveAwardConditionTypeReturnEnum];

