/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentData } from './contentData';


/**
 * Bonus data
 */
export interface BonusData { 
    /**
     * Bonus ID
     */
    bonusId?: number;
    /**
     * List of promotion contents
     */
    bonusContents?: Array<ContentData> | null;
}

