/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BonusSchedulingData { 
    /**
     * Days till activate pending bonus
     */
    timeToActivatePendingBonus?: number | null;
    /**
     * Days till redeem active bonus
     */
    timeToRedeemActiveBonus?: number | null;
    /**
     * Days till accept awarded bonus
     */
    timeToAcceptAwardedBonus?: number | null;
    /**
     * Days till meeting condition for waiting bonus
     */
    timeToMeetConditionsForWaitingBonus?: number | null;
    /**
     * Days till bonus starts contributing to WR
     */
    timeToStartContributingToWR?: number | null;
    /**
     * Time to use free spins for awarded external bonus
     */
    timeToUseFreeSpins?: number | null;
    /**
     * Returns bonus fixed expirty date
     */
    bonusFixedExpiryDate?: string | null;
    /**
     * Configuration value towards which condition bonus goes
     */
    bonusCurrentExpiryCondition?: string | null;
    /**
     * Return date when bonus will expire from configured condition
     */
    bonusCurrentExpiryConditionDate?: string | null;
    /**
     * When the bonus expiration date will accure from expiryJob
     */
    expirationDateReal?: string | null;
    /**
     * Reason why bonus expired
     */
    expirationReason?: string | null;
    /**
     * Bonus start date
     */
    fromDate?: string | null;
    /**
     * Bonus end date
     */
    toDate?: string | null;
}

