/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonusFreeSpins } from './bonusFreeSpins';


export interface BonusProductTypeSummary { 
    /**
     * Bonus balance summary for product type
     */
    bonusBalance?: number;
    /**
     * Product type ID
     */
    productTypeId?: number;
    /**
     * Product type name
     */
    productTypeName?: string | null;
    /**
     * List of Free spin values for free spin bonuses
     */
    freeSpins?: Array<BonusFreeSpins> | null;
}

