/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AwardConditionFulfilmentData } from './awardConditionFulfilmentData';


export interface BonusAwardingData { 
    /**
     * Configuration value towards which condition bonus goes
     */
    awardConditionFulfilment?: Array<AwardConditionFulfilmentData> | null;
    /**
     * Award condition fulfilment operator in case of multiple conditions  Possible values:  * `AND` = all conditions must be met in order to receive bonus  * `OR` = at least one of the conditions must be met in order to receive bonus
     */
    awardConditionFulfilmentOperator?: string | null;
}

