/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonusIncentiveAwardConditionTypeReturnEnum } from './bonusIncentiveAwardConditionTypeReturnEnum';


export interface BonusInfoResponse { 
    /**
     * Unique identifier of the bonus incentive
     */
    bonusIncentiveId?: number;
    /**
     * Translative name of the bonus incentive
     */
    bonusIncentiveFriendlyName?: string | null;
    /**
     * Translative description of the bonus incentive
     */
    bonusIncentiveFriendlyDescription?: string | null;
    /**
     * Time in seconds to meet the conditions of the bonus incentive
     */
    timeToMeetConditions?: number | null;
    /**
     * List of bonus incentive award condition types
     */
    awardConditionTypes?: Array<BonusIncentiveAwardConditionTypeReturnEnum> | null;
}

