/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BonusSettingsData { 
    /**
     * Bonus requiers player opt-in (bonus is linked to a promotion)
     */
    isBonusRequiresOptIn?: boolean | null;
    /**
     * Bonus awarding type (automatic or manual)
     */
    isAutomaticBonus?: boolean | null;
    /**
     * Whether bonus is recurring or not
     */
    isRecurringBonus?: boolean | null;
}

