/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BonusCategoryIdEnum = {
    FirstDeposit: 'FirstDeposit',
    Reload: 'Reload',
    Rebate: 'Rebate',
    Cashback: 'Cashback',
    FreeSpins: 'FreeSpins',
    AwardGames: 'AwardGames',
    Freebet: 'Freebet'
} as const;
export type BonusCategoryIdEnum = typeof BonusCategoryIdEnum[keyof typeof BonusCategoryIdEnum];

