/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cancel withdrawal return
 */
export interface CancelWithdrawalResponse { 
    /**
     * Indicates the status of the cancelled withdrawal.
     */
    paymentStatus?: string | null;
    /**
     * Id of the created transaction.
     */
    transactionId?: string | null;
    /**
     * External error code.
     */
    externalErrorCode?: string | null;
    /**
     * External error message.
     */
    externalErrorMessage?: string | null;
}

