/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cancel withdrawal request
 */
export interface CancelWithdrawalRequest { 
    /**
     * Id of the created transaction.
     */
    transactionId: string;
    /**
     * Reason why the payment was canceled.
     */
    cancelReason?: string | null;
    /**
     * Send true for testing purposes.
     */
    testMode?: boolean | null;
}

