/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangePlayerPasswordAuthRequest { 
    /**
     * Old password
     */
    oldPassword?: string | null;
    /**
     * New password
     */
    newPassword?: string | null;
}

