/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Change Player Password Request
 */
export interface ChangePlayerPasswordRequest { 
    /**
     * Old Passord
     */
    oldPassword: string;
    /**
     * New Password
     */
    newPassword: string;
    /**
     * Flag to terminate other active player\'s site sessions
     */
    terminateOtherSiteSessions?: boolean | null;
}

