/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Change Forgotten Password Request
 */
export interface ChangeForgottenPasswordRequest { 
    /**
     * Secure key should be received via the player\'s email
     */
    secureKey: string;
    /**
     * New password, to replace the forgotten one
     */
    newPassword: string;
}

