/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Message type to change message to read or unread
 */
export const ChangeMessageTypeEnum = {
    Read: 'Read',
    Unread: 'Unread'
} as const;
export type ChangeMessageTypeEnum = typeof ChangeMessageTypeEnum[keyof typeof ChangeMessageTypeEnum];

