/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClaimRewardItemRequestShippingAddress { 
    /**
     * Name of the recipient
     */
    name?: string | null;
    /**
     * Contact number of the recipient
     */
    contactNumber?: string | null;
    /**
     * Email of the recipient
     */
    email?: string | null;
    /**
     * Street address of the recipient
     */
    address?: string | null;
    /**
     * City of the recipient
     */
    city?: string | null;
    /**
     * Postcode of the recipient
     */
    postcode?: string | null;
    /**
     * Country of the recipient
     */
    country?: string | null;
}

