/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClaimRewardItemRequestShippingAddress } from './claimRewardItemRequestShippingAddress';


export interface ClaimRewardItemRequest { 
    /**
     * Id of the reward to be claimed
     */
    rewardId: number;
    /**
     * Required points for the reward that were displayed to the player    If the value is different that the reward\'s actual required points then the reward won\'t be claimed and an error will be returned. This could happen if the required points of the reward were changed while the player was viewing rewards.
     */
    requiredPoints: number;
    shippingAddress?: ClaimRewardItemRequestShippingAddress;
    comment?: string | null;
}

