/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFile } from './mediaFile';
import { Field } from './field';


/**
 * Content field value
 */
export interface ContentFieldValue { 
    /**
     * Currency code
     */
    currencyCode?: string | null;
    /**
     * Language ID
     */
    languageId?: number | null;
    /**
     * Language code
     */
    languageCode?: string | null;
    /**
     * Field ID
     */
    fieldId?: number | null;
    field?: Field;
    /**
     * Value ID
     */
    value?: string | null;
    /**
     * Media file ID
     */
    mediaFileId?: number | null;
    mediaFile?: MediaFile;
}

