/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content schedule
 */
export interface ContentSchedule { 
    /**
     * Start date
     */
    startDate?: string | null;
    /**
     * End date
     */
    endDate?: string | null;
}

