/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content SEO
 */
export interface ContentSeo { 
    /**
     * Language ID
     */
    languageId?: number;
    /**
     * SEO value
     */
    seo?: string | null;
}

