/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content status enumeration
 */
export const ContentStatusEnum = {
    Unpublished: 'Unpublished',
    Published: 'Published',
    Archived: 'Archived'
} as const;
export type ContentStatusEnum = typeof ContentStatusEnum[keyof typeof ContentStatusEnum];

