/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentSeo } from './contentSeo';
import { ContentTypeEnum } from './contentTypeEnum';
import { ContentSubStatusEnum } from './contentSubStatusEnum';
import { ContentStatusEnum } from './contentStatusEnum';
import { ContentFieldValue } from './contentFieldValue';
import { ContentSchedule } from './contentSchedule';


/**
 * Content data
 */
export interface ContentData { 
    /**
     * Banner ID
     */
    id?: number;
    contentType?: ContentTypeEnum;
    /**
     * Banner name
     */
    name?: string | null;
    status?: ContentStatusEnum;
    /**
     * Brand ID
     */
    brandId?: number;
    /**
     * HTML body
     */
    htmlBody?: string | null;
    /**
     * Template ID
     */
    templateId?: number | null;
    subStatus?: ContentSubStatusEnum;
    /**
     * Banner category ID
     */
    categoryId?: number;
    /**
     * Banner category slug
     */
    categorySlug?: string | null;
    /**
     * List of content field values
     */
    contentFieldValues?: Array<ContentFieldValue> | null;
    /**
     * List of label IDs
     */
    labelIds?: Array<number> | null;
    contentSchedule?: ContentSchedule;
    /**
     * List of content SEOs
     */
    contentSeos?: Array<ContentSeo> | null;
    /**
     * Order position
     */
    position?: number;
}
export namespace ContentData {
}


