/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content type enumeration
 */
export const ContentTypeEnum = {
    Ticker: 'Ticker',
    Banner: 'Banner',
    Promotion: 'Promotion',
    Game: 'Game',
    Bonus: 'Bonus'
} as const;
export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];

