/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * In case this property is set, then populating it\'s fields is mandatory.
 */
export interface ContactPrefChannels { 
    /**
     * If the player specifies email as the contact channel.
     */
    email?: boolean;
    /**
     * If the player specifies SMS as the contact channel.
     */
    sms?: boolean;
    /**
     * 
     */
    post?: boolean;
    /**
     * If the player specifies telephone as the contact channel.
     */
    telephone?: boolean;
    /**
     * If the player specifies IM as the contact channel.
     */
    im?: boolean;
    /**
     * If the player specifies popup inbox as the contact channel.
     */
    popupInbox?: boolean;
}

