/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactInfoTypeEnum } from './contactInfoTypeEnum';


/**
 * Contact info type
 */
export interface ContactInfoType { 
    /**
     * Contact info type id
     */
    id?: number;
    /**
     * Contact info type name
     */
    name?: string | null;
    type?: ContactInfoTypeEnum;
}
export namespace ContactInfoType {
}


