/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Contact info verification status response
 */
export interface ContactInfoVerificationStatusResponse { 
    /**
     * Contact info verification status:  * Verified  * NotVerified
     */
    contactInfoVerificationStatus?: string | null;
}

