/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content sub-status enumeration
 */
export const ContentSubStatusEnum = {
    Active: 'Active',
    Inactive: 'Inactive',
    Expired: 'Expired'
} as const;
export type ContentSubStatusEnum = typeof ContentSubStatusEnum[keyof typeof ContentSubStatusEnum];

