/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Country { 
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.
     */
    code?: string | null;
    /**
     * Country name
     */
    name?: string | null;
}

