/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePlayer } from './createPlayer';
import { TrackingSource } from './trackingSource';


/**
 * Create player request.
 */
export interface CreatePlayerRequest { 
    player: CreatePlayer;
    trackingSource?: TrackingSource;
    /**
     * Device fingerprint.
     */
    deviceFingerprint?: string | null;
    /**
     * Flag indicating whether the password is pre-hashed or not.
     */
    preHashedPassword?: boolean | null;
}

