/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderEnum } from './genderEnum';


/**
 * Create player data.
 */
export interface CreatePlayer { 
    /**
     * Username, 16 charaters maximum.
     */
    userName: string;
    /**
     * Password, 6 characters minimum, 30 characters maximum.  IMPORTANT: client implementation is responsible for assuring password complexity.
     */
    password: string;
    /**
     * Valid email address, 50 characters maximum.
     */
    eMail: string;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    firstName: string;
    /**
     * Last name, 2 characters minimum, 50 characters maximum.
     */
    lastName: string;
    /**
     * Middle name, optional. 50 characters maximum.
     */
    middleName?: string | null;
    /**
     * Date of birth in ISO format (YYYY-MM-DD).
     */
    dateOfBirth: string;
    gender?: GenderEnum;
    /**
     * Street name, optional. 130 characters maximum.
     */
    street?: string | null;
    /**
     * House number, optional. 30 characters maximum.
     */
    houseNumber?: string | null;
    /**
     * City, optional. 50 characters maximum.
     */
    city?: string | null;
    /**
     * Post code, optional. 50 characters maximum.
     */
    postalCode?: string | null;
    /**
     * State province, optional. 50 characters maximum.
     */
    stateProvince?: string | null;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode: string;
    /**
     * Portal id. See `GetPortals` for list of supported locales.
     */
    portalId: number;
    /**
     * Currency code in ISO 4217 standard.  See `GetCurrencies` for list of supported currencies.
     */
    currencyCode: string;
    /**
     * Locale.  See `GetLanguages` for list of supported locales.
     */
    locale: string;
    /**
     * Title used to address the player.  See `GetTitles` for more details.
     */
    title?: number | null;
    /**
     * Phone number.
     */
    phoneNumber?: string | null;
    /**
     * Mobile phone number.
     */
    mobilePhone?: string | null;
    /**
     * Secret question, used for security purposes.  See `GetSecretQuestions` for more details.
     */
    secretQuestionId?: number | null;
    /**
     * Secret answer, used for security purposes. 255 characters maximum
     */
    secretAnswer?: string | null;
    /**
     * Coupon code for bonuses.  NOTICE: this will be overriden if the `CouponCode` is set in the `TrackingSource` object.
     */
    couponCode?: string | null;
    /**
     * Flag indicating whether the player wants to receive marketing offers and bonuses.
     */
    receiveNews?: boolean | null;
    /**
     * Nickname, 50 characters maximum (numbers, letters, `-`, and `_`).
     */
    nickname?: string | null;
    /**
     * Product type id.                Additional registration info. Portal provides Id for the selected product type id, from where registration is triggered. If provided its being validated againts existing product type within IGS.  See `GetProductTypes` for more details.
     */
    productTypeId?: number | null;
    /**
     * Flag that indicates that player will not be market as internal, although it was created from a whitelisted device or IP.
     */
    ignoreInternalAccountsWhiteListSetting?: boolean | null;
    /**
     * Instant messenger handle.
     */
    instantMessenger?: string | null;
    /**
     * Instant messenger type.  See `GetContactInfoTypes` for more details.
     */
    instantMessengerType?: number | null;
    /**
     * Additional custom parameters.
     */
    customParameters?: { [key: string]: string; } | null;
    /**
     * Flag indicating whether multi-factor authentication should be enabled.
     */
    useMFA?: boolean | null;
    /**
     * Flag indicating whether the player wants to receive SMS from operator.
     */
    receiveSMSFromOperator?: boolean | null;
    /**
     * Flag indicating whether the player wants to receive e-mail from operator.
     */
    receiveEmailFromOperator?: boolean | null;
    /**
     * Terms and Conditions version that the player agreed to at register time.
     */
    tcVersion?: string | null;
}
export namespace CreatePlayer {
}


