/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Newly created player info.
 */
export interface CreatePlayerResponse { 
    /**
     * ID of the newly created player.
     */
    playerId?: number;
    /**
     * Flag indicating whether the newly created player is activated or not.
     */
    isPlayerActivated?: boolean;
    /**
     * Status of referral on the creation
     */
    referralStatus?: string | null;
}

