/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Currency { 
    /**
     * Currency code in ISO 4217 standard.
     */
    code?: string | null;
    /**
     * Currency name
     */
    name?: string | null;
}

