/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomContent { 
    /**
     * Language of this custom content  (empty = ALL)
     */
    language?: string | null;
    /**
     * Type of the content
     */
    type?: string | null;
    /**
     * Content Value
     */
    content?: string | null;
}

