/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeclineMultiChoiceBonusRequest { 
    /**
     * Bonus Group ID
     */
    bonusGroupId: number;
    /**
     * Group Instance Id
     */
    groupInstanceId?: string | null;
}

