/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeclinePlayerBonusContextRequest { 
    /**
     * Player bonus context ID
     */
    playerBonusContextId: number;
    /**
     * Player wants to decline recurrence or only single context
     */
    declineRecurrence?: boolean | null;
}

