/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DocumentCategoryEnum = {
    PhotoId: 'PhotoId',
    ProofOfAdress: 'ProofOfAdress',
    ProofOfPaymentMethod: 'ProofOfPaymentMethod',
    DepositDeclaration: 'DepositDeclaration',
    Miscellaneous: 'Miscellaneous',
    UploadedFromPortal: 'UploadedFromPortal'
} as const;
export type DocumentCategoryEnum = typeof DocumentCategoryEnum[keyof typeof DocumentCategoryEnum];

