/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerDocument } from './playerDocument';


/**
 * Contact info verification status response
 */
export interface DocumentsResponse { 
    /**
     * Array of information on users uploaded documents
     */
    documents?: Array<PlayerDocument> | null;
    /**
     * Number of records in \"Documents\" array
     */
    recordCount?: number;
}

