/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Exclude player request.
 */
export interface ExcludePlayerRequest { 
    /**
     * Until the player is self-excluded. Date must be between SelfExcludeMinDays (180) and SelfExcludeMaxDays (1825).
     */
    excludedUntil: string;
}

