/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaceAuthenticationProcessStatusEnum } from './faceAuthenticationProcessStatusEnum';


export interface FaceAuthProcessResponse { 
    status?: FaceAuthenticationProcessStatusEnum;
}
export namespace FaceAuthProcessResponse {
}


