/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FaceAuthResponse { 
    /**
     * Reference id to be used in facial authentication status check
     */
    referenceId?: string | null;
    /**
     * Url to open to the player
     */
    url?: string | null;
    /**
     * Url to QR code
     */
    quickResponseCodeUrl?: string | null;
}

