/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Update player via face auth
 */
export interface FaceAuthUpdatePlayerRequest { 
    /**
     * Player ID.
     */
    id?: number;
    /**
     * Valid email address, 50 characters maximum.
     */
    eMail: string;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    firstName: string;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    lastName: string;
    /**
     * City, 50 characters maximum.
     */
    city?: string | null;
    /**
     * Post code, optional. 50 characters maximum.
     */
    postalCode?: string | null;
    /**
     * Mobile phone number.
     */
    mobilePhone?: string | null;
    /**
     * Street name, optional. 130 characters maximum.
     */
    street?: string | null;
    /**
     * House number, optional. 30 characters maximum.
     */
    houseNumber?: string | null;
}

