/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentTypeEnum } from './contentTypeEnum';
import { FieldType } from './fieldType';


/**
 * Field
 */
export interface Field { 
    /**
     * Field ID
     */
    id?: number;
    contentType?: ContentTypeEnum;
    /**
     * Field type ID
     */
    fieldTypeId?: number;
    /**
     * Is field translatable
     */
    translatable?: boolean;
    /**
     * Field name
     */
    name?: string | null;
    /**
     * Placeholder text
     */
    placeholderText?: string | null;
    /**
     * Field order
     */
    order?: number | null;
    /**
     * Is field visible
     */
    visible?: boolean | null;
    fieldType?: FieldType;
}
export namespace Field {
}


