/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player forgot username request
 */
export interface ForgotUsernameRequest { 
    /**
     * Player\'s email
     */
    email: string;
    /**
     * Playe\'s secret question id    Use `globalization/secret-questions` to get a list of all secret questions
     */
    secretQuestionId?: number | null;
    /**
     * The answer to the secret question
     */
    answer?: string | null;
    /**
     * Portal id
     */
    portalId: number;
}

