/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ForgotPasswordFaceAuthRequest { 
    /**
     * CPF number
     */
    cpfNumber: string;
    /**
     * The player\'s email
     */
    email?: string | null;
    /**
     * The player\'s date of birth                This parameter is optional and configurable.
     */
    dateOfBirth?: string;
    /**
     * The secret question id which the player uses for password resetting, to get all secret question id\'s use globalization/secret-questions                This parameter is optional and configurable.
     */
    secretQuestionId?: string | null;
    /**
     * Player\'s answer to his specified secret question                This parameter is optional and configurable.
     */
    answer?: string | null;
    /**
     * Portal id
     */
    portalId: number;
    /**
     * Domain, this parameter is optional                This parameter is optional and configurable.
     */
    domain?: string | null;
}

