/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Game Parameters
 */
export interface GameParameters { 
    /**
     * Parameter name
     */
    name?: string | null;
    /**
     * Parameter value
     */
    value?: string | null;
}

