/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameMainTranslation } from './gameMainTranslation';
import { GameParameters } from './gameParameters';


/**
 * List of games in the category.
 */
export interface GameMain { 
    /**
     * Game ID.
     */
    id?: number | null;
    /**
     * External game ID.
     */
    externalId?: string | null;
    /**
     * Product supplier ID.
     */
    productSupplierId?: number | null;
    /**
     * Product supplier name.
     */
    productSupplierName?: string | null;
    /**
     * Product ID.
     */
    productId?: number | null;
    /**
     * Product name.
     */
    productName?: string | null;
    /**
     * Game name.
     */
    name?: string | null;
    /**
     * Name of game.
     */
    gameName?: string | null;
    /**
     * Flag indicating whether game supports free play.
     */
    demoPlayRestricted?: boolean | null;
    /**
     * Flag indicating whether game supports real play.
     */
    realPlayRestricted?: boolean | null;
    /**
     * Flag indicating whether the game is in maintenance.
     */
    maintenanceModeEnabled?: boolean | null;
    /**
     * List of Progressive Jackpot IDs, associated with the game.
     */
    progressiveJackpots?: Array<string> | null;
    /**
     * List of translations.
     */
    translations?: Array<GameMainTranslation> | null;
    /**
     * Game type name.
     */
    gameTypeName?: string | null;
    /**
     * Game type ID.
     */
    gameTypeId?: number | null;
    /**
     * Game Parameters
     */
    parameters?: Array<GameParameters> | null;
}

