/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameCategoryType } from './gameCategoryType';


/**
 * CategoryTypes response.
 */
export interface GameCategoryTypesResponse { 
    /**
     * List of Category types.
     */
    categoryTypes?: Array<GameCategoryType> | null;
    /**
     * Number of returned records.
     */
    recordCount?: number | null;
}

