/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List of translations
 */
export interface GameMainTranslation { 
    /**
     * Name of the field.
     */
    fieldName?: string | null;
    /**
     * Translated string
     */
    fieldTranslation?: string | null;
}

