/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GamesModel { 
    /**
     * Internal game ID
     */
    gameId?: number;
    /**
     * External game ID
     */
    externalGameId?: string | null;
    /**
     * Internal game name
     */
    gameName?: string | null;
    /**
     * Supplier game name
     */
    supplierGameName?: string | null;
    /**
     * Channel name like \"Internet\", \"Mobile\"...
     */
    channelName?: string | null;
}

