/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Game status.    Possible values:  * Active,   * Finished,  * Voided
 */
export const GameCycleStatusEnum = {
    Active: 'Active',
    Finished: 'Finished',
    Voided: 'Voided'
} as const;
export type GameCycleStatusEnum = typeof GameCycleStatusEnum[keyof typeof GameCycleStatusEnum];

