/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameCategory } from './gameCategory';


export interface GameCategoriesResponse { 
    gameCategoryList?: Array<GameCategory> | null;
    recordCount?: number | null;
}

