/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GenderEnum = {
    Male: 'Male',
    Female: 'Female'
} as const;
export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];

