/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeolocationConfigurationResponse { 
    /**
     * The client\'s IP
     */
    clientIP?: string | null;
    /**
     * The country code of the client (geolocation)
     */
    countryCode?: string | null;
    /**
     * The default currency for the resolved geolocation
     */
    defaultCurrency?: string | null;
    /**
     * Available languages for the resolved geolocation
     */
    languages?: Array<string> | null;
}

