/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonusProductTypeSummary } from './bonusProductTypeSummary';
import { PlayerBonusHistory } from './playerBonusHistory';


export interface GetBonusResponse { 
    /**
     * Bonus balance
     */
    bonusBalance?: number;
    /**
     * Bonus summary per product type
     */
    bonusSummaryPerProductType?: Array<BonusProductTypeSummary> | null;
    /**
     * Bonus history
     */
    playerBonusHistory?: Array<PlayerBonusHistory> | null;
    /**
     * Response created timestamp
     */
    responseCreatedDate?: string | null;
}

