/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonusInfoResponse } from './bonusInfoResponse';


export interface GetBonusesInfoResponse { 
    /**
     * Lift of bonus\' information
     */
    bonuses: Array<BonusInfoResponse> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

