/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerOptInBonus } from './playerOptInBonus';


export interface GetBonusesAvailableForOptInReturn { 
    bonusBalance?: number;
    playerOptInBonuses?: Array<PlayerOptInBonus> | null;
    responseCreatedDate?: string | null;
}

