/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


/**
 * Get balance return
 */
export interface GetBalanceResponse { 
    /**
     * List of accounts (wallets).
     */
    accounts?: Array<Account> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

