/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Betinfo } from './betinfo';


/**
 * Get bet history return
 */
export interface GetBetHistoryResponse { 
    /**
     * List of history bets
     */
    historyList?: Array<Betinfo> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

