/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RewardData } from './rewardData';


export interface GetClaimableRewardsResponse { 
    /**
     * Reward list
     */
    rewardList?: Array<RewardData> | null;
}

