/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get General Lobby For Product Request
 */
export interface GetGeneralLobbyForProductRequestATL { 
    /**
     * Product for which the general lobby is getting retrieved.
     */
    product: string;
    /**
     * Optional parameter. ProductSupplier for which the general lobby is getting retrieved. Used when you want to find the plugin by product supplier instead of by product. Used for aggregate game providers for which the customer wants to add new products without any code change on iCore side.
     */
    productSupplier?: string | null;
    /**
     * Player\'s language code.
     */
    languageCode: string;
    /**
     * Additional parameters(key, value) that are customer specific.
     */
    properties?: { [key: string]: string; } | null;
}

