/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameMain } from './gameMain';


export interface GetGameMainsResponse { 
    /**
     * List of Games.
     */
    gameMainList?: Array<GameMain> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

