/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameParameters } from './gameParameters';


export interface GetGameParametersResponse { 
    /**
     * List of parameter names and values
     */
    gameParameters?: Array<GameParameters> | null;
    /**
     * Number of parameters
     */
    recordCount?: number;
}

