/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageExtended } from './messageExtended';


/**
 * Get messages return
 */
export interface GetMessagesResponse { 
    /**
     * List of messages
     */
    messages?: Array<MessageExtended> | null;
    /**
     * Number of returned records
     */
    recordCount?: number | null;
}

