/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LimitStatusEnum } from './limitStatusEnum';
import { TimeTypeEnum } from './timeTypeEnum';
import { LimitTypeEnum } from './limitTypeEnum';


/**
 * A player\'s limit, regarding single bet, game session duration, total wager and lost.    Each of the LimitType can have two two entries in the return list(one active, and one pending).
 */
export interface GetPlayerLimit { 
    /**
     * Id of the limit.
     */
    id?: number;
    limitType?: LimitTypeEnum;
    limitStatus?: LimitStatusEnum;
    time?: TimeTypeEnum;
    /**
     * Amount of the limit, unit is defined by LimitType.
     */
    amountValue?: number | null;
    /**
     * Amount of the limit left.
     */
    amountLeft?: number | null;
    /**
     * If the limit is locked. If it\'s then set it to true, if not then set it to false.
     */
    locked?: boolean;
    /**
     * Reason for the limit.
     */
    reason?: string | null;
    /**
     * Date of limit creation.
     */
    dateCreated?: string;
    /**
     * Date of limit activation.
     */
    dateActivated?: string | null;
}
export namespace GetPlayerLimit {
}


