/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentTransactionTypeEnum } from './paymentTransactionTypeEnum';


/**
 * Get player transactions request
 */
export interface GetPlayerTransactionsRequest { 
    /**
     * Manual transactions
     */
    withManualTransactions?: boolean;
    /**
     * Retrieve child transactions
     */
    retrieveChildTransactions?: boolean;
    /**
     * Beginning date of transaction
     */
    fromDate: string;
    /**
     * End date of transaction
     */
    toDate: string;
    /**
     * Number of entries on page
     */
    pageSize: number;
    /**
     * Number of the page
     */
    pageNumber: number;
    transactionType?: PaymentTransactionTypeEnum;
}
export namespace GetPlayerTransactionsRequest {
}


