/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactPrefChannels } from './contactPrefChannels';
import { ProductTypeParamExtended } from './productTypeParamExtended';


/**
 * Get player contact preferences response.
 */
export interface GetPlayerContactPreferencesResponse { 
    /**
     * Flag indicating whether player would like to receive emails from operator.
     */
    receiveEmailFromOperator?: boolean;
    /**
     * Flag indicating whether player would like to receive sms from operator.
     */
    receiveSMSFromOperator?: boolean;
    /**
     * Flag indicating whether player would like to receive exclusive offers and bonuses.
     */
    receiveExclusiveOffersAndBonuses?: boolean;
    /**
     * Flag indicating whether player would like to receive email from third party.
     */
    receiveEmailFromThirdParty?: boolean;
    /**
     * Flag indicating whether player would like to receive sms from third party.
     */
    receiveSMSFromThirdParty?: boolean;
    /**
     * Block all.
     */
    blockAll?: boolean;
    /**
     * Do not call the player.
     */
    doNotCall?: boolean;
    /**
     * Flag indicating whether player would like to opt-in for profiling.
     */
    optinProfiling?: boolean;
    /**
     * Receive land-based retail info.
     */
    receiveLandBasedRetailInfo?: boolean;
    /**
     * Receive login notification.
     */
    receiveLoginNotification?: boolean;
    contactPrefChannels?: ContactPrefChannels;
    /**
     * List of product types.
     */
    productTypes?: Array<ProductTypeParamExtended> | null;
}

