/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get player segments response.
 */
export interface GetPlayerSegmentsResponse { 
    /**
     * List of marketing segments player is in
     */
    segmentIds?: Array<number> | null;
}

