/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get player bonuses request
 */
export interface GetPlayerBonusesRequest { 
    /**
     * Category key list
     */
    slugs: Array<string>;
    /**
     * Bonus Incentive IDs
     */
    bonusIncentiveIds: Array<number>;
    /**
     * Language code
     */
    languageCode: string;
}

