/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transaction } from './transaction';


/**
 * Get player transactions return
 */
export interface GetPlayerTransactionsResponse { 
    /**
     * List of transaction
     */
    transactions?: Array<Transaction> | null;
    /**
     * Number of returned records
     */
    recordcount?: number;
    /**
     * Records limit exceeded
     */
    recordsLimitExceeded?: boolean;
}

