/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get quick payment settings request.
 */
export interface GetQuickPaymentSettingsRequest { 
    /**
     * Optional Currency code as in ISO-4217 standard, if not given player currency is used.
     */
    currency?: string | null;
}

