/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get quick payment settings response.
 */
export interface GetQuickPaymentSettingsResponse { 
    /**
     * List of quick payment settings.
     */
    settings?: Array<number> | null;
}

