/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductAvailability } from './productAvailability';
import { ProductSupplierAvailability } from './productSupplierAvailability';
import { PortalAvailability } from './portalAvailability';


/**
 * Restrictions response
 */
export interface GetRestrictionsResponse { 
    /**
     * List of availabilities for different products
     */
    productAvailability?: Array<ProductAvailability> | null;
    /**
     * List of product supplier availabilities information
     */
    productSupplierAvailability?: Array<ProductSupplierAvailability> | null;
    portalAvailability?: PortalAvailability;
}

