/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecretQuestion } from './secretQuestion';


/**
 * Get secret questions return
 */
export interface GetSecretQuestionsResponse { 
    /**
     * List of secret questions
     */
    secretQuestions?: Array<SecretQuestion> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

