/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Title } from './title';


export interface GetTitlesResponse { 
    /**
     * Get titles return
     */
    titles?: Array<Title> | null;
    /**
     * Number of returned records
     */
    recordCount?: number;
}

