/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Get unread messages count return.
 */
export interface GetUnreadMessagesCountResponse { 
    /**
     * The number of unread messages.
     */
    unreadCount?: number | null;
    /**
     * The number of unread messages in the pop-up.
     */
    unreadPopupCount?: number | null;
}

