/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameCycleStatusEnum } from './gameCycleStatusEnum';


/**
 * List of history.
 */
export interface History { 
    /**
     * Game cycle Id.
     */
    id?: string | null;
    /**
     * Game name.
     */
    name?: string | null;
    /**
     * Game start time.
     */
    start?: string | null;
    /**
     * Game stop time.
     */
    stop?: string | null;
    /**
     * Bet value.
     */
    stake?: number | null;
    /**
     * Won value - Total/Net depends on bonus configuration.
     */
    won?: number | null;
    /**
     * Game/Bet description.
     */
    summary?: string | null;
    status?: GameCycleStatusEnum;
    /**
     * Product type (Casino, Poker, SportsBook).
     */
    productType?: string | null;
    /**
     * External game Id.
     */
    externalGameId?: string | null;
    /**
     * Product Id.
     */
    productId?: number;
    /**
     * Product name.
     */
    productName?: string | null;
    /**
     * Product supplier.
     */
    productSupplier?: string | null;
}
export namespace History {
}


