/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const KYCOnboardingStatusEnum = {
    Created: 'CREATED',
    Processing: 'PROCESSING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;
export type KYCOnboardingStatusEnum = typeof KYCOnboardingStatusEnum[keyof typeof KYCOnboardingStatusEnum];

