/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameMain } from './gameMain';


/**
 * List of categories.
 */
export interface LevelDataGameMain { 
    /**
     * ID of the category.
     */
    id?: number | null;
    /**
     * ID of the parent category.
     */
    parentId?: number | null;
    /**
     * Category name.
     */
    name?: string | null;
    /**
     * Name of game.
     */
    gameName?: string | null;
    /**
     * List of sub-categories.
     */
    subLevel?: Array<LevelDataGameMain> | null;
    /**
     * List of games in the category.
     */
    gameMains?: Array<GameMain> | null;
    /**
     * Category type.
     */
    levelType?: string | null;
}

