/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible limit statuses.    Possible  values:  * Active,  * Pending,  * Canceled,  * Expired
 */
export const LimitStatusEnum = {
    Active: 'Active',
    Pending: 'Pending',
    Canceled: 'Canceled',
    Expired: 'Expired'
} as const;
export type LimitStatusEnum = typeof LimitStatusEnum[keyof typeof LimitStatusEnum];

