/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of player limits.    Possible  values:  * TotalWager,  * TotalLost,  * GameSessionDuration,  * MaxSingleBet,  * Deposit,  * SiteSessionDuration
 */
export const LimitTypeEnum = {
    TotalWager: 'TotalWager',
    TotalLost: 'TotalLost',
    GameSessionDuration: 'GameSessionDuration',
    MaxSingleBet: 'MaxSingleBet',
    Deposit: 'Deposit',
    SiteSessionDuration: 'SiteSessionDuration'
} as const;
export type LimitTypeEnum = typeof LimitTypeEnum[keyof typeof LimitTypeEnum];

