/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Message } from './message';
import { TrackingData } from './trackingData';
import { LogonSession } from './logonSession';


export interface LoginResponseExtended { 
    /**
     * List of messages
     */
    messages?: Array<Message> | null;
    logonSession?: LogonSession;
    /**
     * Failed login count
     */
    failedLoginCount?: number | null;
    /**
     * Last login time
     */
    lastLoginTime?: string | null;
    /**
     * Last login IP
     */
    lastLoginIp?: string | null;
    /**
     * Player token.  Used when player data is incomplete or change username is required.
     */
    playerToken?: string | null;
    /**
     * Flag indicating whether the player is created by agent
     */
    isPlayerCreatedByAgent?: boolean | null;
    tracking?: TrackingData;
    /**
     * Status code
     */
    statusCode?: string | null;
    /**
     * AdditionalData
     */
    additionalData?: { [key: string]: string; } | null;
    /**
     * Reference Id
     */
    referenceId?: string | null;
    /**
     * ReVerification URL
     */
    reverificationUrl?: string | null;
    /**
     * QR Code ReVerification URL
     */
    quickResponseCodeReverificationUrl?: string | null;
}

