/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginRequest { 
    /**
     * Player\'s username.  In case that the product’s login type is specified as Nickname or Email, username parameter can also be filled out with player nickname or email.
     */
    userName: string;
    /**
     * Player\'s password.
     */
    password: string;
    /**
     * Portal ID in which the player will login.
     */
    portalId: number;
    /**
     * Device fingerprint
     */
    deviceFingerprint?: string | null;
    /**
     * Flag indicating whether to include notifications.
     */
    includeNotifications?: boolean | null;
    /**
     * Flag indicating whether the player\'s client device is mobile.
     */
    mobileClient?: boolean | null;
    /**
     * Player\'s date of birth.
     */
    dateOfBirth?: string | null;
    /**
     * External Device ID
     */
    externalDeviceId?: string | null;
}

