/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of the player\'s logon session.    Posible values:  * Active,  * Cloesed,  * Incomplete.
 */
export const LogonSessionStatusEnum = {
    Active: 'Active',
    Closed: 'Closed',
    Incomplete: 'Incomplete'
} as const;
export type LogonSessionStatusEnum = typeof LogonSessionStatusEnum[keyof typeof LogonSessionStatusEnum];

