/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogonSessionStatusEnum } from './logonSessionStatusEnum';


/**
 * Logon session detail.
 */
export interface LogonSessionDetail { 
    /**
     * Player logon time.
     */
    logonTime?: string;
    /**
     * Player logout time.
     */
    logoutTime?: string | null;
    /**
     * Client IP.
     */
    clientIp?: string | null;
    /**
     * Real client IP.
     */
    realClientIp?: string | null;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode?: string | null;
    status?: LogonSessionStatusEnum;
}
export namespace LogonSessionDetail {
}


