/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Loyalty transaction.
 */
export interface LoyaltyTransaction { 
    /**
     * Date time of the redeem transaction.
     */
    date?: string;
    /**
     * Number of redeemed point.
     */
    points?: number;
    /**
     * Type of points.
     */
    pointType?: number;
    /**
     * Name of type.
     */
    pointTypeName?: string | null;
    /**
     * Conversion rate of redeemed points.
     */
    rate?: number | null;
    /**
     * Real money amount.
     */
    amount?: number | null;
}

