/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of player segments.                Possible  values:  * Default,  * ForWebUsage
 */
export const MarketingSegmentTypeEnum = {
    Default: 'Default',
    ForWebUsage: 'ForWebUsage'
} as const;
export type MarketingSegmentTypeEnum = typeof MarketingSegmentTypeEnum[keyof typeof MarketingSegmentTypeEnum];

