/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Media file
 */
export interface MediaFile { 
    /**
     * Media file ID
     */
    id?: number | null;
    /**
     * Brand ID
     */
    brandId?: number;
    /**
     * Media file name
     */
    name?: string | null;
    /**
     * Media file extension
     */
    extension?: string | null;
    /**
     * Media file path
     */
    path?: string | null;
    /**
     * Media file external URL
     */
    url?: string | null;
    /**
     * Media file size in bytes
     */
    size?: number | null;
    /**
     * Media file size beautified
     */
    sizePretty?: string | null;
}

