/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTypeEnum } from './messageTypeEnum';
import { PopupAction } from './popupAction';


/**
 * Message
 */
export interface Message { 
    /**
     * Message id
     */
    id?: number | null;
    /**
     * List of all actions
     */
    actions?: Array<PopupAction> | null;
    /**
     * Message title
     */
    title?: string | null;
    /**
     * Created message date
     */
    createdDate?: string | null;
    /**
     * Contents message
     */
    contents?: string | null;
    messageType?: MessageTypeEnum;
    /**
     * Message subtype
     */
    messageSubtype?: string | null;
    /**
     * Message group
     */
    messageGroup?: string | null;
}
export namespace Message {
}


