/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Message type  Possible values:  * LoginPopup,  * GameStartPopup,  * WithdrawalPopup,  * InboxNotification,  * BlockPopup,  * ConsolePopup
 */
export const MessageTypeEnum = {
    LoginPopup: 'LoginPopup',
    GameStartPopup: 'GameStartPopup',
    WithdrawalPopup: 'WithdrawalPopup',
    InboxNotification: 'InboxNotification',
    BlockPopup: 'BlockPopup',
    ConsolePopup: 'ConsolePopup'
} as const;
export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];

