/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MinMaxAmountData { 
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Minimum amount
     */
    min?: number | null;
    /**
     * Maximum amount  NOTE: null in case of AwardTimeType = Immediately
     */
    max?: number | null;
    /**
     * Sequential number of deposit which will trigger the awarding (present only for Deposit trigger type – 0 = any deposit)
     */
    sequentialNumberOfDeposit?: number | null;
}

