/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultiChoiceBonusInfo { 
    /**
     * Bonus incentive ID
     */
    bonusIncetiveId?: number;
    /**
     * Bonus incentive name
     */
    bonusIncetiveName?: string | null;
    /**
     * Bonus incentive friendly name
     */
    bonusIncetiveFriendlyName?: string | null;
    /**
     * Bonus incentive friendly description
     */
    bonusIncetiveFriendlyDescription?: string | null;
    /**
     * Is this multi-choice bonus chosen for awarding (chosen=true, declined=false, null=not yet chosen from this group)
     */
    bonusMultiBonusChosen?: boolean | null;
    /**
     * Multi-choice bonus group ID
     */
    bonusGroupId?: number | null;
    /**
     * Player bonus incentive context ID
     */
    playerBonusContextId?: number | null;
    /**
     * Multichoice bonus group instance id
     */
    groupInstanceId?: string | null;
}

