/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KYCOnboardingStatusEnum } from './kYCOnboardingStatusEnum';


export interface OnboardingCheckResponse { 
    onboardingStatus?: KYCOnboardingStatusEnum;
}
export namespace OnboardingCheckResponse {
}


