/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrackingSource } from './trackingSource';


export interface OnboardingRequest { 
    /**
     * Players username
     */
    userName: string;
    /**
     * Password, 8 characters minimum.  IMPORTANT: client implementation is responsible for assuring password complexity.
     */
    password: string;
    /**
     * Valid email address, 50 characters maximum.
     */
    email: string;
    /**
     * Portal ID in which the player will login.
     */
    portalId: number;
    /**
     * CPF number
     */
    cpf: string;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode: string;
    /**
     * Currency code in ISO 4217 standard.
     */
    currencyCode: string;
    /**
     * Locale.  See `GetLanguages` for list of supported locales.
     */
    locale: string;
    /**
     * Fingerprint of the device.
     */
    deviceFingerprint?: string | null;
    trackingSource?: TrackingSource;
    /**
     * Phone number.
     */
    phoneNumber?: string | null;
}

