/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OnboardingResponse { 
    referenceId?: string | null;
    url?: string | null;
    quickResponseCodeUrl?: string | null;
}

