/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AwardConditionFulfilmentData } from './awardConditionFulfilmentData';


export interface OptInBonusAwardingData { 
    awardConditionFulfilment?: Array<AwardConditionFulfilmentData> | null;
    awardConditionFulfilmentOperator?: string | null;
}

