/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentTypeEnum } from './paymentInstrumentTypeEnum';


/**
 * Payment request.
 */
export interface PaymentRequest { 
    /**
     * ID of the product.
     */
    productId?: number | null;
    /**
     * ID of payment instrument.
     */
    paymentInstrumentId?: number | null;
    paymentInstrumentType?: PaymentInstrumentTypeEnum;
    /**
     * ID of payment account.
     */
    paymentAccountId?: number | null;
    /**
     * Id of the payment provider.
     */
    paymentProviderId?: number | null;
    /**
     * Bonus code
     */
    bonusCode?: string | null;
    /**
     * Amount of transaction.
     */
    amount?: number | null;
    /**
     * Currency code as in ISO-4217 standard.
     */
    currency?: string | null;
    /**
     * Fingerprint of the device – used for device management services, such as Iovation.
     */
    deviceFingerprint?: string | null;
    /**
     * Additional information about the deposit (depending on the payment instrument used).
     */
    parameters?: { [key: string]: string; } | null;
    /**
     * Send true for testing purposes.
     */
    testMode?: boolean | null;
}
export namespace PaymentRequest {
}


