/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentTypeEnum } from './paymentInstrumentTypeEnum';


/**
 * Paymen instrument data.
 */
export interface PaymentInstrumentData { 
    /**
     * ID of payment instrument.
     */
    id?: number | null;
    /**
     * Name of the payment instrument.
     */
    name?: string | null;
    /**
     * External ID
     */
    externalId?: string | null;
    paymentInstrumentType?: PaymentInstrumentTypeEnum;
    /**
     * Whether a credit card was used. Set to true if it’s a credit card.
     */
    isCreditCard?: boolean | null;
    /**
     * Supports performing deposits.
     */
    supportsDeposit?: boolean | null;
    /**
     * Supports performing withdrawals.
     */
    supportsWithdrawal?: boolean | null;
    /**
     * ID of payment provider.
     */
    paymentProviderId?: number | null;
}
export namespace PaymentInstrumentData {
}


