/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentData } from './paymentInstrumentData';


/**
 * Payment instruments data return
 */
export interface PaymentInstrumentsDataResponse { 
    /**
     * List of all available payment instruments.
     */
    paymentInstruments?: Array<PaymentInstrumentData> | null;
    /**
     * External error code.
     */
    externalErrorCode?: string | null;
    /**
     * External error message.
     */
    externalErrorMessage?: string | null;
}

