/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment Account
 */
export interface PaymentAccount { 
    /**
     * Account id.
     */
    accountId?: number;
    /**
     * Payment instrument id: 22 – LocalBankTransfer(bank accounts)
     */
    paymentInstrumentId?: number;
    /**
     * Visual representation of the account.
     */
    displayName?: string | null;
    /**
     * DateTime when it was last used, can be null.
     */
    lastUsedTime?: string | null;
    agreement?: boolean | null;
    /**
     * Flag if account is enabled for withdrawal.
     */
    enabledForWithdrawal?: boolean;
    /**
     * Flag if account is enabled for deposit.
     */
    enabledForDeposit?: boolean;
    /**
     * Account properties such as TokenID, Name…
     */
    properties?: { [key: string]: string; } | null;
}

