/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment instrument type.  Possible values:  * Card,  * BankTransfer,  * Alternative,   * Online,  * Crypto
 */
export const PaymentInstrumentTypeEnum = {
    Card: 'Card',
    BankTransfer: 'BankTransfer',
    Alternative: 'Alternative',
    Online: 'Online',
    Crypto: 'Crypto'
} as const;
export type PaymentInstrumentTypeEnum = typeof PaymentInstrumentTypeEnum[keyof typeof PaymentInstrumentTypeEnum];

