/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlayerBonusInfo { 
    /**
     * Bonus incentive ID
     */
    bonusIncetiveId?: number | null;
    /**
     * Bonus incentive name
     */
    bonusIncetiveName?: string | null;
    /**
     * Bonus incentive friendly name
     */
    bonusIncetiveFriendlyName?: string | null;
    /**
     * Player ID
     */
    playerId?: number | null;
}

