/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlayerStatusesResponse { 
    playerStatus?: boolean;
    kycStatus?: boolean;
    kycAnnualVerificationRequired?: boolean;
    email?: boolean;
    phoneNumber?: boolean;
    address?: boolean;
    sigapReady?: boolean;
    calculatedStatus?: boolean;
}

