/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Record of Player Shortcut Game
 */
export interface PlayerShortcutGameMain { 
    /**
     * Extenral game id
     */
    gameExternalId?: string | null;
    /**
     * Player id
     */
    playerId?: number | null;
    /**
     * Date when the shortcut was created.
     */
    marketDate?: string | null;
    /**
     * Internal game name
     */
    gameName?: string | null;
    /**
     * Game Type
     */
    gameType?: string | null;
    /**
     * Product name
     */
    product?: string | null;
}

