/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player game request.
 */
export interface PlayerGameRequest { 
    /**
     * External game id to start game.
     */
    extGameId: string;
    /**
     * ID of  the application / portal.
     */
    portalId: number;
    /**
     * Flag indicating whether the game is in real play.   True (play for real), False (play for fun).
     */
    realPlay: boolean;
    /**
     * Flag indicating whether game is launched in native.
     */
    isNative: boolean;
    /**
     * Player\'s current (selected) language.
     */
    language: string;
    /**
     * Additional launch parameters.
     */
    properties?: { [key: string]: string; } | null;
    /**
     * Specify in which currency the game should be lunched
     */
    desiredCurrency?: string | null;
}

