/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player statuses.  Possible  values:  * Initial  * Incomplete  * Created  * Active  * SelfExcluded  * Suspended  * ClosedByCompany  * ClosedByPlayer  * AwaitingVerification  * TimedOut
 */
export const PlayerStatusEnum = {
    Initial: 'Initial',
    Incomplete: 'Incomplete',
    Created: 'Created',
    Active: 'Active',
    SelfExcluded: 'SelfExcluded',
    Suspended: 'Suspended',
    ClosedByCompany: 'ClosedByCompany',
    ClosedByPlayer: 'ClosedByPlayer',
    AwaitingVerification: 'AwaitingVerification',
    TimedOut: 'TimedOut'
} as const;
export type PlayerStatusEnum = typeof PlayerStatusEnum[keyof typeof PlayerStatusEnum];

