/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerShortcutGameMain } from './playerShortcutGameMain';


export interface PlayerShortcutGameMainsResponse { 
    /**
     * List of Player Shortcut Games
     */
    games?: Array<PlayerShortcutGameMain> | null;
    /**
     * Number of returned records
     */
    recordCount?: number | null;
}

