/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player validate data result
 */
export interface PlayerValidateDataResult { 
    /**
     * Returns the field for which the value is being validated
     */
    type?: string | null;
    /**
     * Status of players validated data  Status:  * Success,  * CouponNotFound,  * PrincipalExist,  * EmailExists,  * ContainsBannedWord
     */
    status?: string | null;
}

