/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player contact info.
 */
export interface PlayerContactInfo { 
    /**
     * Sub-type ID.  Possible values:  * 1 – home,   * 2 - mobile1,   * 3 - mobile2,   * 4 – work,   * 5 - fax,   * 6 - other
     */
    subTypeId?: number;
    /**
     * Type ID.
     */
    typeId?: number;
    /**
     * If preferred.
     */
    preferred?: boolean;
    /**
     * Value.
     */
    value?: string | null;
    /**
     * If contact is verified.
     */
    verified?: boolean;
    /**
     * Name of contact player.
     */
    name?: string | null;
}

