/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerContactInfo } from './playerContactInfo';
import { PlayerStatusEnum } from './playerStatusEnum';
import { GenderEnum } from './genderEnum';
import { SecretQuestionAndAnswer } from './secretQuestionAndAnswer';


/**
 * All player details.
 */
export interface PlayerDetails { 
    /**
     * Player ID to retrieve players\' data and details.
     */
    id?: number | null;
    /**
     * ID of  the application / portal.   See `GetPortals` for list of supported locales.
     */
    portalId?: number | null;
    /**
     * If player is active.
     */
    activePlayer?: boolean;
    /**
     * Secret question, used for security purposes.  See method \"GET  /api/portal/v1/globalization/secret-questions\" for more details.
     */
    secretQuestionId?: number | null;
    /**
     * Security question.
     */
    securityQuestion?: number | null;
    /**
     * Secret answer, used for security purposes.
     */
    secretAnswer?: string | null;
    /**
     * Security answer.
     */
    securityAnswer?: string | null;
    /**
     * First name of the player.
     */
    firstName?: string | null;
    /**
     * Last name of the player.
     */
    lastName?: string | null;
    /**
     * Middle name of the player.
     */
    middleName?: string | null;
    /**
     * Date of birth in ISO format (YYYY-MM-DD).
     */
    dateOfBirth?: string | null;
    /**
     * Currency code in ISO 4217 standard.  See `GetCurrencies` for list of supported currencies.
     */
    currencyCode?: string | null;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode?: string | null;
    gender?: GenderEnum;
    /**
     * City.
     */
    city?: string | null;
    /**
     * Postal code.
     */
    postalCode?: string | null;
    /**
     * Street.
     */
    street?: string | null;
    /**
     * House number.
     */
    houseNumber?: string | null;
    /**
     * Player\'s email.
     */
    eMail?: string | null;
    /**
     * Locale code(culture or language core) of the player   See `GetLanguages` for list of supported locales.
     */
    locale?: string | null;
    /**
     * Username of the player
     */
    userName?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Signup IP address. Not publicly available.
     */
    signupIp?: string | null;
    /**
     * Title used to address the player.  See `GetTitles` for more details.
     */
    title?: number | null;
    /**
     * State province.
     */
    stateProvince?: string | null;
    /**
     * Hear about us.
     */
    hearAboutUs?: string | null;
    /**
     * Coupon code for bonuses.
     */
    couponCode?: string | null;
    /**
     * Flag indicating whether the player wants to receive marketing offers and bonuses.
     */
    receiveNews?: boolean | null;
    /**
     * GeoLocation country code.
     */
    geoLocCountryCode?: string | null;
    /**
     * If mobile client.
     */
    mobileClient?: boolean | null;
    /**
     * Player nickname.
     */
    nickname?: string | null;
    /**
     * Product type ID.
     */
    productTypeId?: string | null;
    /**
     * Affiliate external ID.
     */
    affiliateExternalId?: string | null;
    /**
     * Player registration date.
     */
    registrationDate?: string;
    /**
     * Ignoring internal accounts whitelist settings
     */
    ignoreInternalAccountsWhiteListSetting?: boolean;
    /**
     * Type of instant messenger
     */
    instantMessengerType?: number;
    /**
     * Instant messenger
     */
    instantMessenger?: string | null;
    /**
     * Mobile phone number.
     */
    mobilePhone?: string | null;
    /**
     * List of contact info about the player.
     */
    contactInfo?: Array<PlayerContactInfo> | null;
    /**
     * Additional custom parameters.
     */
    customParameters?: { [key: string]: string | null; } | null;
    /**
     * List of secret questions and answers.
     */
    secretQuestionsAndAnswers?: Array<SecretQuestionAndAnswer> | null;
    /**
     * Flag indicating whether multi-factor authentication should be enabled.
     */
    useMFA?: boolean | null;
    /**
     * Id of channel used for MFA.
     */
    mfaChannel?: number | null;
    /**
     * Flag indicating whether multi-factor authentication is locked.
     */
    mfaLocked?: boolean | null;
    /**
     * If internal account.
     */
    internalAccount?: boolean | null;
    /**
     * Registration portal ID.
     */
    registrationPortalId?: number | null;
    status?: PlayerStatusEnum;
}
export namespace PlayerDetails {
}


