/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlayerKycStatusEnum = {
    Unknown: 'Unknown',
    Passed: 'Passed',
    Delayed: 'Delayed',
    Failed: 'Failed',
    PartiallyVerified: 'PartiallyVerified',
    KycReverification: 'KYCReverification',
    KycReverificationFailed: 'KYCReverificationFailed'
} as const;
export type PlayerKycStatusEnum = typeof PlayerKycStatusEnum[keyof typeof PlayerKycStatusEnum];

