/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptedInEnum } from './optedInEnum';


export interface PlayerOptInCodeWithPlayerPromotionsRequest { 
    /**
     * Opt-in code
     */
    optInCode: string;
    /**
     * Promotion ID
     */
    promotionId?: number | null;
    /**
     * Language code
     */
    languageCode?: string | null;
    /**
     * Brand ID
     */
    brandId?: number | null;
    /**
     * Flag indicating whether to include custom content. Default = false.
     */
    includeCustomContent?: boolean | null;
    optedIn?: OptedInEnum;
    /**
     * Possible options:  False or not provided: all promotions  True: promotions that are linked to Multi choice bonus configuration
     */
    multiChoiceBonus?: boolean | null;
    /**
     * Flag to check eligibility only for bonuses linked to specific promotion instead for all bonuses. Default value is false.
     */
    eligibilityCheckForPromotionBonusesOnly?: boolean;
    /**
     * Flag to also include player bonuses from history table (player bonuses in final state and older than 2 weeks). Default value is true (configurable - BonusMgmt.GetPlayerBonuses.DefaultIncludeHistory).
     */
    includeHistory?: boolean | null;
}
export namespace PlayerOptInCodeWithPlayerPromotionsRequest {
}


