/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Player validate data
 */
export interface PlayerValidateData { 
    /**
     * Represents the field for which the value is being validated  * Username  * BonusPromoCode,  * Email,  * BannedWords
     */
    type: string;
    /**
     * Value to be validated for key
     */
    value: string;
}

