/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlayerBonusHistoryStatusEnum = {
    Declined: 'Declined',
    Active: 'Active',
    Pending: 'Pending',
    Expired: 'Expired',
    Frozen: 'Frozen',
    Lost: 'Lost',
    Redeemed: 'Redeemed',
    Waiting: 'Waiting',
    WaitingManual: 'WaitingManual',
    AwardedExternal: 'AwardedExternal',
    AwardWaiting: 'AwardWaiting',
    FinancialApproval: 'FinancialApproval',
    WaitingExternal: 'WaitingExternal',
    UnsuccessfulExternalAwarding: 'UnsuccessfulExternalAwarding',
    RedeemWaiting: 'RedeemWaiting',
    WaitingEligibility: 'WaitingEligibility'
} as const;
export type PlayerBonusHistoryStatusEnum = typeof PlayerBonusHistoryStatusEnum[keyof typeof PlayerBonusHistoryStatusEnum];

