/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerDetails } from './playerDetails';


/**
 * Player details return.
 */
export interface PlayerDetailsResponse { 
    player?: PlayerDetails;
}

