/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of player tokens.    Possible  values:  * ForgotPasswordToken,  * PlayerActivationToken,  * IncompleteRegistrationToken,  * ChangeUserNameToken,  * UpdateMarketingToken,  * ReferAFriendEmailToken  * SMSVerificationToken  * ReferAFriendSMSToken  * OTPToken  * EmailVerificationToken  * MultiFactorAuthenticationToken  * SingleSignOnToken  * PlayerSessionRenewalToken  * OTPWithdrawal  * TransferSessionToken
 */
export const PlayerTokenTypeEnum = {
    ForgotPasswordToken: 'ForgotPasswordToken',
    PlayerActivationToken: 'PlayerActivationToken',
    IncompleteRegistrationToken: 'IncompleteRegistrationToken',
    ChangeUserNameToken: 'ChangeUserNameToken',
    UpdateMarketingToken: 'UpdateMarketingToken',
    ReferAFriendEmailToken: 'ReferAFriendEmailToken',
    SmsVerificationToken: 'SMSVerificationToken',
    ReferAFriendSmsToken: 'ReferAFriendSMSToken',
    OtpToken: 'OTPToken',
    EmailVerificationToken: 'EmailVerificationToken',
    MultiFactorAuthenticationToken: 'MultiFactorAuthenticationToken',
    SingleSignOnToken: 'SingleSignOnToken',
    PlayerSessionRenewalToken: 'PlayerSessionRenewalToken',
    OtpWithdrawal: 'OTPWithdrawal',
    TransferSessionToken: 'TransferSessionToken'
} as const;
export type PlayerTokenTypeEnum = typeof PlayerTokenTypeEnum[keyof typeof PlayerTokenTypeEnum];

