/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomContent } from './customContent';
import { OptInBonusAwardingData } from './optInBonusAwardingData';
import { BonusOptInSchedulingData } from './bonusOptInSchedulingData';


export interface PlayerOptInBonus { 
    bonusId?: number;
    playerBonusId?: number;
    status?: number;
    bonusName?: string | null;
    bonusFriendlyName?: string | null;
    termAndConditionsId?: number | null;
    bonusMultiBonusChosen?: boolean | null;
    expirationDate?: string | null;
    productTypeName?: string | null;
    bonusType?: string | null;
    categoryId?: number | null;
    bonusDescription?: string | null;
    bonusFriendlyDescription?: string | null;
    bonusScheduling?: BonusOptInSchedulingData;
    bonusAwarding?: OptInBonusAwardingData;
    bonusAmount?: number;
    externalBonusProductSupplier?: string | null;
    externalBonusProduct?: string | null;
    bonusCustomContentList?: Array<CustomContent> | null;
}

