/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalStatusEnum } from './approvalStatusEnum';


/**
 * Player Document.
 */
export interface PlayerDocument { 
    /**
     * Document Id.
     */
    id?: number;
    /**
     * File name with file extension.
     */
    name?: string | null;
    approvalStatus?: ApprovalStatusEnum;
    /**
     * UTC DateTime of uploaded document.
     */
    creationTime?: string;
    /**
     * Expiration DateTime of the uploaded document.
     */
    expirationTime?: string | null;
    /**
     * Category of the uploaded document.
     */
    documentCategory?: number | null;
    /**
     * Document number
     */
    documentNumber?: string | null;
    /**
     * National id
     */
    nationalId?: string | null;
    /**
     * Document series
     */
    seriesNumber?: string | null;
}
export namespace PlayerDocument {
}


