/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Message popup state  Possible  values:  * Pending,  * Read,  * Unread,  * Expired,  * Inactive,  * OneTime,  * Deleted
 */
export const PopupStateEnum = {
    Pending: 'Pending',
    Read: 'Read',
    Unread: 'Unread',
    Expired: 'Expired',
    Inactive: 'Inactive',
    OneTime: 'OneTime',
    Deleted: 'Deleted'
} as const;
export type PopupStateEnum = typeof PopupStateEnum[keyof typeof PopupStateEnum];

