/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Popup action
 */
export interface PopupAction { 
    /**
     * Popup action id
     */
    id?: number | null;
    /**
     * Popup action name
     */
    name?: string | null;
    /**
     * Action type
     */
    actionType?: number | null;
}

