/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailabilityFlags } from './availabilityFlags';


/**
 * Portal availability
 */
export interface PortalAvailability { 
    /**
     * Portal Id
     */
    portalId?: number;
    /**
     * If true, the country is restricted
     */
    isCountryRestricted?: boolean;
    /**
     * If true, the currency is restricted
     */
    isCurrencyRestricted?: boolean;
    avbl?: AvailabilityFlags;
}

