/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * In case this property is set, then populating it\'s fields is mandatory.
 */
export interface ProductTypeParam { 
    /**
     * ID of product type.
     */
    productTypeId?: number;
    /**
     * If promotion mail was received.
     */
    recievePromoEmail?: boolean;
}

