/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailabilityFlags } from './availabilityFlags';


/**
 * Product supplier availability
 */
export interface ProductSupplierAvailability { 
    /**
     * Product supplier ID
     */
    productSupplierId?: number;
    /**
     * Product supplier name
     */
    productSupplierName?: string | null;
    avbl?: AvailabilityFlags;
}

