/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailabilityFlags } from './availabilityFlags';


/**
 * Product availability
 */
export interface ProductAvailability { 
    /**
     * Product id
     */
    productId?: number;
    /**
     * Product name
     */
    productName?: string | null;
    /**
     * Country restriction, if true, the product cannot be used in the specific country
     */
    isCountryRestricted?: boolean;
    /**
     * Currency restriction, if true, the product cannot be used with the specific currency
     */
    isCurrencyRestricted?: boolean;
    avbl?: AvailabilityFlags;
}

