/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Product type parameters extended.
 */
export interface ProductTypeParamExtended { 
    /**
     * ID of product type.
     */
    productTypeId?: number;
    /**
     * If promotion mail was received.
     */
    recievePromoEmail?: boolean;
    /**
     * Product type name.
     */
    productTypeName?: string | null;
}

