/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PromotionStatusEnum = {
    NotYetOptedin: 'NotYetOptedin',
    OptedIn: 'OptedIn',
    OptedOut: 'OptedOut',
    NoOptinRequired: 'NoOptinRequired'
} as const;
export type PromotionStatusEnum = typeof PromotionStatusEnum[keyof typeof PromotionStatusEnum];

