/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentData } from './contentData';


/**
 * Promotion data
 */
export interface PromotionData { 
    /**
     * Promotion ID
     */
    promotionId?: number;
    /**
     * List of promotion contents
     */
    promotionContents?: Array<ContentData> | null;
}

