/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromotionsOptOutRequest { 
    /**
     * Coupon event ID
     */
    couponEventId: number;
    /**
     * Promotion ID
     */
    promotionId: number;
    /**
     * Flag indicating whether to decline all related bonuses
     */
    declineAllRelatedBonuses: boolean;
}

