/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Create redeem loyalty points request.
 */
export interface RedeemLoyaltyPointsRequest { 
    /**
     * Number of points.
     */
    numberOfPoints: number;
}

