/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoyaltyTransaction } from './loyaltyTransaction';


/**
 * Create redeemed points transactions return.
 */
export interface RedeemedPointsTransactionsResponse { 
    /**
     * List of redeemed marketing points transactions.
     */
    loyaltyTransactions?: Array<LoyaltyTransaction> | null;
    /**
     * Number of returned records.
     */
    recordCount?: number;
}

