/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferAFriend } from './referAFriend';


/**
 * Refer a friend response.
 */
export interface ReferAFriendResponse { 
    /**
     * Refer a friend request valid boolean, true if valid, false if invalid.
     */
    rafRequestValid?: boolean;
    /**
     * A list of referees that were referred.
     */
    referAFriend?: Array<ReferAFriend> | null;
}

