/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Refer a friend data.
 */
export interface ReferAFriend { 
    /**
     * Name of the referee.
     */
    name?: string | null;
    /**
     * Contact of the referee.
     */
    refereeContact?: string | null;
    /**
     * Error code.
     */
    errorCode?: string | null;
}

