/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Referee\'s contact information
 */
export interface RefereeContactInformation { 
    /**
     * Referee contact
     */
    contact?: string | null;
    /**
     * Referee name
     */
    name?: string | null;
}

