/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Refer a Friend statistics return.
 */
export interface ReferAFriendStatisticsResponse { 
    /**
     * The total number of invited friends.
     */
    total?: number;
    /**
     * The total number of invited friends who have registered and also deposited the necessary amount.
     */
    successful?: number;
    /**
     * The total number of registered friends who haven\'t (yet) deposited the necessary amount.
     */
    currentRegistered?: number;
    /**
     * The total number of bonuses issued on the base of referrals.
     */
    totalReferalBonuses?: number;
}

