/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Refer a friend request type
 */
export const RequestTypeEnum = {
    Email: 'Email',
    Sms: 'SMS'
} as const;
export type RequestTypeEnum = typeof RequestTypeEnum[keyof typeof RequestTypeEnum];

