/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReVerificationResponse { 
    /**
     * Reference Id
     */
    referenceId?: string | null;
    /**
     * Url that needs to be opened
     */
    url?: string | null;
    /**
     * URL with QR code
     */
    quickResponseCodeUrl?: string | null;
}

