/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RewardTypeEnum } from './rewardTypeEnum';
import { RewardTag } from './rewardTag';
import { RewardStatusEnum } from './rewardStatusEnum';


export interface RewardData { 
    /**
     * Id of the reward
     */
    rewardId?: number;
    /**
     * Name of the reward
     */
    name?: string | null;
    /**
     * Required amount of points to claim the reward
     */
    requiredPoints?: number;
    /**
     * Description of the reward
     */
    description?: string | null;
    rewardType?: RewardTypeEnum;
    rewardStatus?: RewardStatusEnum;
    /**
     * Recommended flag
     */
    recommended?: boolean;
    /**
     * New flag
     */
    'new'?: boolean;
    /**
     * Date since when the reward is available. If null then there is no limit since when it is available.
     */
    startDate?: string | null;
    /**
     * Date until when the reward is available. If null then there is no limit until when it is available.
     */
    endDate?: string | null;
    /**
     * Date when the reward was created
     */
    createdDate?: string;
    /**
     * Reward tags
     */
    tags?: Array<RewardTag> | null;
}
export namespace RewardData {
}


