/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Secret question and answer.
 */
export interface SecretQuestionAndAnswer { 
    /**
     * Secret question, used for security purposes.  See method \"GET  /api/portal/v1/globalization/secret-questions\" for more details.
     */
    secretQuestionId?: number;
    /**
     * Secret answer, used for security purposes.
     */
    secretAnswer?: string | null;
}

