/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SecretQuestion { 
    /**
     * Id of the secret question
     */
    id?: number;
    /**
     * Secret question
     */
    question?: string | null;
}

