/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SetPlayerLimit } from './setPlayerLimit';


export interface SetPlayerLimitRequest { 
    limit?: SetPlayerLimit;
}

