/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeTypeEnum } from './timeTypeEnum';
import { LimitTypeEnum } from './limitTypeEnum';


/**
 * A player\'s limit, regarding single bet, game session duration, total wager and lost.    Each of the LimitType can have two two entries in the return list(one active, and one pending)
 */
export interface SetPlayerLimit { 
    limitType: LimitTypeEnum;
    time?: TimeTypeEnum;
    /**
     * Amount of the limit, unit is defined by LimitType
     */
    amountValue?: number | null;
    /**
     * Reason for the limit
     */
    reason?: string | null;
}
export namespace SetPlayerLimit {
}


