/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This parameter is requred if LimitType is set to Deposit.  Possible time types:  * Hours,  * Day,  * Week,  * Month,  * GameSession,
 */
export const TimeTypeEnum = {
    Hour: 'Hour',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month',
    GameSession: 'GameSession'
} as const;
export type TimeTypeEnum = typeof TimeTypeEnum[keyof typeof TimeTypeEnum];

