/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Title
 */
export interface Title { 
    /**
     * Title id
     */
    id?: number;
    /**
     * Title name
     */
    name?: string | null;
    /**
     * Description of a title
     */
    description?: string | null;
}

