/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Top Winners Item
 */
export interface TopWinnersATL { 
    /**
     * Players Id
     */
    playerId?: string | null;
    /**
     * Players username
     */
    username?: string | null;
    /**
     * External Game Id
     */
    gameExternalId?: string | null;
    /**
     * Name of the game
     */
    gameName?: string | null;
    /**
     * Product Name
     */
    productName?: string | null;
    /**
     * Amount
     */
    amount?: string | null;
    /**
     * Currency Id
     */
    currencyId?: string | null;
    /**
     * Currency Code
     */
    currencyCode?: string | null;
    /**
     * Win Date
     */
    winDate?: string | null;
    /**
     * Amount
     */
    betAmount?: string | null;
}

