/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrackingData { 
    /**
     * Marketing channel
     */
    marketingChannel?: string | null;
    /**
     * Marketing source
     */
    marketingSource?: string | null;
    /**
     * Campaign name
     */
    campaignName?: string | null;
}

