/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tracking source data.
 */
export interface TrackingSource { 
    /**
     * Marketing channel.
     */
    marketingChannel?: string | null;
    /**
     * Marketing source.
     */
    marketingSource?: string | null;
    /**
     * Campaign name.
     */
    campaignName?: string | null;
    /**
     * Coupon code.  NOTICE: this will override the `CouponCode` set in the `Player` object.
     */
    couponCode?: string | null;
    /**
     * Creative.
     */
    creative?: string | null;
    /**
     * Content.
     */
    content?: string | null;
    /**
     * BTag.
     */
    btag?: string | null;
    /**
     * Additional custom parameters.
     */
    customFields?: { [key: string]: string; } | null;
}

