/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionDetailsInfo } from './transactionDetailsInfo';


/**
 * Transaction details response
 */
export interface TransactionDetailsResponse { 
    /**
     * List of transactions
     */
    transactionDetailsInfo?: Array<TransactionDetailsInfo> | null;
}

