/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Transaction { 
    /**
     * Transaction id
     */
    id?: string | null;
    /**
     * Status of transaction
     */
    status?: number;
    /**
     * Transaction creation time.
     */
    createTime?: string;
    /**
     * Type of transaction
     */
    type?: number;
    /**
     * Amount transacted
     */
    amount?: number;
    /**
     * Transaction reference from Payment
     */
    referenceObject?: string | null;
    /**
     * Multipurpose description field that can be used by operator to store different kind of information about transaction
     */
    additionalDescription?: string | null;
    /**
     * Balance after the transaction was performed
     */
    balanceAfter?: number;
    /**
     * Payment provider name
     */
    providerName?: string | null;
    /**
     * Flag that indicates if the transaction is cancellable
     */
    isCancellable?: boolean;
    /**
     * Id of the sending product
     */
    productId?: number | null;
    /**
     * Payment instrument name
     */
    paymentInstrumentName?: string | null;
}

