/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Transaction details
 */
export interface TransactionDetailsInfo { 
    /**
     * Transaction id
     */
    id?: number;
    /**
     * Transaction type
     */
    transactionTypeName?: string | null;
    /**
     * Transaction created time
     */
    createTime?: string;
    /**
     * Reference object
     */
    referenceObject?: string | null;
    /**
     * Transaction step id
     */
    transactionStepId?: number;
    /**
     * Transaction step type
     */
    transactionStepTypeName?: string | null;
    /**
     * Credit type name
     */
    creditTypeName?: string | null;
    /**
     * Step time
     */
    stepTime?: string;
    /**
     * Transaction amount
     */
    amount?: number;
    /**
     * Transaction amount after
     */
    amountAfter?: number | null;
    /**
     * Transaction amount before
     */
    amountBefore?: number | null;
}

