/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Transaction details request
 */
export interface TransactionDetailsRequest { 
    /**
     * Transaction reference
     */
    referenceObject?: string | null;
}

