/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecretQuestionAndAnswer } from './secretQuestionAndAnswer';


/**
 * Update player.
 */
export interface UpdatePlayer { 
    /**
     * City, 50 characters maximum.
     */
    city?: string | null;
    /**
     * Country code in Alpha-2 ISO 3166-1 standard.  See `GetCountries` for list of supported countries.
     */
    countryCode: string;
    /**
     * Date of birth in ISO format (YYYY-MM-DD).
     */
    dateOfBirth?: string;
    /**
     * Valid email address, 50 characters maximum.
     */
    eMail: string;
    /**
     * First name, 2 characters minimum, 50 characters maximum.
     */
    firstName: string;
    /**
     * Gender.
     */
    gender?: string | null;
    /**
     * House number, optional. 30 characters maximum.
     */
    houseNumber?: string | null;
    /**
     * Player ID.
     */
    id?: number;
    /**
     * Last name, 2 characters minimum, 50 characters maximum.
     */
    lastName: string;
    /**
     * List of supported languages.
     */
    locale: string;
    /**
     * Middle name, optional. 50 characters maximum.
     */
    middleName?: string | null;
    /**
     * Mobile phone number.
     */
    mobilePhone?: string | null;
    /**
     * Nickname, 50 characters maximum (numbers, letters, `-`, and `_`).
     */
    nickname?: string | null;
    /**
     * Phone number.
     */
    phoneNumber?: string | null;
    /**
     * Vip level in poker.
     */
    pokerViplevel?: string | null;
    /**
     * Post code, optional. 50 characters maximum.
     */
    postalCode?: string | null;
    /**
     * State province, optional. 50 characters maximum.
     */
    stateProvince?: string | null;
    /**
     * Street name, optional. 130 characters maximum.
     */
    street?: string | null;
    /**
     * Secret answer, used for security purposes.  Possible values:  * Mother’s Maiden Name  * Father’s First Name  * Name of your First Car  * Name of your First Pet   * Name of your First School
     */
    securityAnswer?: string | null;
    /**
     * Secret question, used for security purposes.
     */
    securityQuestion?: number | null;
    /**
     * Title used to address the player.  Possible values:   * Mr,  * Mrs,   * Miss,  * Ms,   * Dr,   * Sir,   * Other
     */
    title?: number | null;
    /**
     * List of the secret questions and answers.
     */
    secretQuestionsAndAnswers?: Array<SecretQuestionAndAnswer> | null;
    /**
     * Flag indicating whether multi-factor authentication should be enabled.
     */
    useMFA?: boolean | null;
    /**
     * Id of channel used for MFA.
     */
    mfaChannel?: number | null;
    /**
     * Additional custom parameters.
     */
    customParameters?: { [key: string]: string; } | null;
}

