/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentTypeEnum } from './paymentInstrumentTypeEnum';


/**
 * Update player payment account.
 */
export interface UpdatePlayerPaymentAccountRequest { 
    paymentInstrumentType?: PaymentInstrumentTypeEnum;
    /**
     * ID of payment instrument.
     */
    paymentInstrumentId?: number | null;
    /**
     * Payment provider id
     */
    paymentProviderId?: number | null;
    /**
     * Payment account data to be updated, entires depend on the payment instrument.
     */
    parameters?: { [key: string]: string; } | null;
    /**
     * Send true for testing purposes.
     */
    testMode?: boolean;
}
export namespace UpdatePlayerPaymentAccountRequest {
}


