/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatePlayer } from './updatePlayer';


/**
 * Update player request.
 */
export interface UpdatePlayerRequest { 
    player: UpdatePlayer;
}

