/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeParam } from './productTypeParam';
import { ContactPrefChannels } from './contactPrefChannels';


/**
 * Update player contact preferences request
 */
export interface UpdatePlayerContactPrefRequest { 
    /**
     * Flag indicating whether player would like to receive emails from operator
     */
    receiveEmailFromOperator?: boolean | null;
    /**
     * Flag indicating whether player would like to receive SMS from operator
     */
    receiveSMSFromOperator?: boolean | null;
    /**
     * Flag indicating whether player would like to receive exclusive offers and bonuses
     */
    receiveExclusiveOffersAndBonuses?: boolean | null;
    /**
     * Flag indicating whether player would like to receive email from third party
     */
    receiveEmailFromThirdParty?: boolean | null;
    /**
     * Flag indicating whether player would like to receive SMS from third party
     */
    receiveSMSFromThirdParty?: boolean | null;
    /**
     * Flag indicating whether player would like to block all
     */
    blockAll?: boolean | null;
    /**
     * lag indicating whether player would like to receive calls
     */
    doNotCall?: boolean | null;
    /**
     * Flag indicating whether player would like to opt-in for profiling
     */
    optinProfiling?: boolean | null;
    /**
     * Flag indicating whether player would like to receive land based retail info
     */
    receiveLandBasedRetailInfo?: boolean | null;
    /**
     * Flag indicating whether player would like to receive login notification
     */
    receiveLoginNotification?: boolean | null;
    contactPrefChannels?: ContactPrefChannels;
    /**
     * Product types parameters
     */
    productTypes?: Array<ProductTypeParam> | null;
}

