/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerValidateData } from './playerValidateData';


/**
 * Validate player data request
 */
export interface ValidatePlayerDataRequest { 
    /**
     * Portal id
     */
    portalId: number;
    /**
     * List of players data
     */
    playerDataList: Array<PlayerValidateData>;
}

