/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WageringContributionModeEnum = {
    Wagering: 'Wagering',
    Chunks: 'Chunks',
    WagerCount: 'WagerCount',
    WageringAndWagerCount: 'WageringAndWagerCount',
    WageringOrWagerCount: 'WageringOrWagerCount'
} as const;
export type WageringContributionModeEnum = typeof WageringContributionModeEnum[keyof typeof WageringContributionModeEnum];

