/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WageringRequirementChunkTypeEnum = {
    Wager: 'Wager',
    BonusPoints: 'BonusPoints'
} as const;
export type WageringRequirementChunkTypeEnum = typeof WageringRequirementChunkTypeEnum[keyof typeof WageringRequirementChunkTypeEnum];

