/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WagerTypeEnum = {
    PreWager: 'PreWager',
    AfterWager: 'AfterWager'
} as const;
export type WagerTypeEnum = typeof WagerTypeEnum[keyof typeof WagerTypeEnum];

