/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Withdrawal fee configuration
 */
export interface WithdrawalFeeConfiguration { 
    /**
     * ID of payment method.
     */
    paymentMethodId?: number | null;
    /**
     * Payment method.
     */
    paymentMethod?: string | null;
    /**
     * ID of payment provider.
     */
    paymentProviderId?: number | null;
    /**
     * The payment provider.
     */
    paymentProvider?: string | null;
    /**
     * Value of the fee amount.
     */
    feeAmount?: number | null;
    /**
     * Fee type.
     */
    feeType?: string | null;
    /**
     * Value from the amount of withdrawal.
     */
    fromAmount?: number | null;
    /**
     * Value to the amount of withdrawal.
     */
    toAmount?: number | null;
}

