/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WithdrawalFaceAuthProcessStatusEnum = {
    Processing: 'Processing',
    Rejected: 'Rejected',
    Approved: 'Approved',
    Unknown: 'Unknown'
} as const;
export type WithdrawalFaceAuthProcessStatusEnum = typeof WithdrawalFaceAuthProcessStatusEnum[keyof typeof WithdrawalFaceAuthProcessStatusEnum];

