/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawalFee } from './withdrawalFee';
import { PlayerKycStatusEnum } from './playerKycStatusEnum';


/**
 * Withdrawal eligibility parameters return
 */
export interface WithdrawalEligibilityParametersResponse { 
    /**
     * Is KYC passed.
     */
    kycStatusPassed?: boolean;
    /**
     * Bank transfer eligibility for withdrawal.
     */
    eligibleForBankTransferWithdrawal?: boolean;
    /**
     * CICO transfer eligibility.
     */
    eligibleForCicoWithdrawal?: boolean;
    /**
     * Online transfer eligibility for withdrawal.
     */
    eligibleForOnlineWithdrawal?: boolean;
    /**
     * Bonus expiration trigger for withdrawal.
     */
    willAnyBonusExpireOnWithdrawal?: boolean;
    withdrawalFees?: WithdrawalFee;
    kycStatus?: PlayerKycStatusEnum;
    /**
     * Active player accounts count
     */
    activePlayerAccountsCount?: number;
    /**
     * Inctive player accounts count
     */
    inactivePlayerAccountsCount?: number;
}
export namespace WithdrawalEligibilityParametersResponse {
}


