/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawalFaceAuthProcessStatusEnum } from './withdrawalFaceAuthProcessStatusEnum';


export interface WithdrawalFaceAuthProcessResponse { 
    /**
     * URL to redirect the player to in case of additional external authorization.
     */
    redirectURL?: string | null;
    /**
     * Method for launching.
     */
    webMethod?: string | null;
    /**
     * If the request has been confirmed (true/false).
     */
    confirmRequired?: boolean | null;
    /**
     * Reason why the payment was declined.
     */
    declineReason?: string | null;
    /**
     * Reason code why the payment was declined.
     */
    declineReasonCode?: string | null;
    /**
     * Additional information about the deposit (depending on the payment instrument used).
     */
    parameters?: { [key: string]: string; } | null;
    /**
     * Id of the created transaction
     */
    transactionId?: string | null;
    /**
     * Status of the created payment.
     */
    paymentStatus?: string | null;
    /**
     * External error code.
     */
    externalErrorCode?: string | null;
    /**
     * External error message.
     */
    externalErrorMessage?: string | null;
    withdrawalFacialAuthProcessStatus?: WithdrawalFaceAuthProcessStatusEnum;
}
export namespace WithdrawalFaceAuthProcessResponse {
}


