/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawalFeeConfiguration } from './withdrawalFeeConfiguration';


/**
 * Withdrawal fee
 */
export interface WithdrawalFee { 
    /**
     * Withdrawal fee enabled flag.
     */
    withdrawalFeeEnabled?: boolean | null;
    /**
     * Free withdrawal fees in period amount.
     */
    freeWithdrawalFeesInPeriod?: number;
    /**
     * Withdrawal fee start period.
     */
    withdrawalFeeStartPeriod?: string | null;
    /**
     * Withdrawal fee end period.
     */
    withdrawalFeeEndPeriod?: string | null;
    /**
     * Withdrawals fees count.
     */
    withdrawalsFeesCount?: number | null;
    /**
     * List of withdrawal fees settings.
     */
    withdrawalFeesSettings?: Array<WithdrawalFeeConfiguration> | null;
}

