/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawalEligibilityStatusEnum } from './withdrawalEligibilityStatusEnum';


export interface WithdrawalEligibilityCheckResponse { 
    status?: WithdrawalEligibilityStatusEnum;
    /**
     * Indicates if withdrawal process can proceed
     */
    abortFurtherProcessing?: boolean;
    /**
     * Decline reason
     */
    declineReason?: string | null;
    /**
     * Withdrawal facial authentication status
     */
    declineReasonCode?: string | null;
}
export namespace WithdrawalEligibilityCheckResponse {
}


