/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WithdrawalEligibilityStatusEnum = {
    Unknown: 'Unknown',
    Approved: 'Approved',
    Declined: 'Declined'
} as const;
export type WithdrawalEligibilityStatusEnum = typeof WithdrawalEligibilityStatusEnum[keyof typeof WithdrawalEligibilityStatusEnum];

