/**
 * PortalGateway.ATL.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonusAmountPerCurrency } from './bonusAmountPerCurrency';
import { MinMaxAmountData } from './minMaxAmountData';


export interface WithdrawalRequestBonusInfo { 
    /**
     * Bonus incentive Id
     */
    bonusIncentiveId?: number;
    /**
     * Bonus incentive friendly name
     */
    bonusIncentiveFriendlyName?: string | null;
    /**
     * Bonus incentive friendly description
     */
    bonusIncentiveFriendlyDescription?: string | null;
    /**
     * Bonus incentive terms and conditions
     */
    bonusIncentiveTermsAndConditions?: string | null;
    /**
     * Is multi-choice bonus chosen
     */
    bonusMultiBonusChosen?: boolean;
    /**
     * Player bonus incentive context Id
     */
    playerBonusContextId?: number;
    /**
     * Product type Id
     */
    productTypeId?: number | null;
    /**
     * Bonus group Id
     */
    bonusGroupId?: number | null;
    /**
     * Bonus fixed amount for all currencies
     */
    bonusAmountFixedSameForAll?: number | null;
    /**
     * Bonus fixed amount by currency
     */
    bonusAmountFixedPerCurrency?: Array<BonusAmountPerCurrency> | null;
    /**
     * Bonus amount percentage
     */
    bonusAmountPercentage?: number | null;
    /**
     * Bonus percentage of amount for all currencies
     */
    bonusPercentageUpToMaxAmountSameForAll?: number | null;
    /**
     * Bonus percentage of amount by currency
     */
    bonusPercentageUpToMaxAmountPerCurrency?: Array<BonusAmountPerCurrency> | null;
    /**
     * Awarding condition withdrawal request min amount for all currencies
     */
    awardingConditionWithdrawalRequestAmountSameForAllMin?: number | null;
    /**
     * Awarding condition withdrawal request max amount for all currencies
     */
    awardingConditionWithdrawalRequestAmountSameForAllMax?: number | null;
    /**
     * Awarding condition withdrawal request min max amounts per currency
     */
    awardingConditionWithdrawalRequestMinMaxAmountsPerCurrency?: Array<MinMaxAmountData> | null;
}

