import { BreakpointObserver } from '@angular/cdk/layout';
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  OnInit,
  ViewChild,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GameCategoriesService, ProvidersLobbyEnum } from '@app/@core/game-categories.service';
import { AppBreakpoints } from '@app/@shared/app-breakpoints';
import { AssetsService } from '@app/@shared/assets.service';
import { GameProviderDataWithUrl } from '@app/@shared/models';
import { GamesService } from '@app/@shared/services/games/games.service';
import { switchMap } from 'rxjs';
import { SwiperOptions } from 'swiper';

@Component({
  selector: 'app-providers',
  templateUrl: './providers.component.html',
  styleUrls: ['./providers.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProvidersComponent implements OnInit {
  @ViewChild('gameGridContainer', { static: true }) providerGridContainer!: ElementRef<HTMLElement>;
  @Input() initialLoadAmount = 10;
  @Input() initialRows = 2; // how many rowst to show initially, 0 is for auto
  @Input() showOnlyInitialRows = true; // should list show only initialRows (no auto rows) ?
  @Input() isProvidersPage = false;
  @Input() showArrowsMobile = true;

  missingImgUrl = this.assetsService.cdnizeUrl('assets/general/logo/game-placeholder.jpg');

  providersList: GameProviderDataWithUrl[] | null = null;

  allProvidersCount = 0;

  // css string to specify rows in grid layout (so we can do it without js)
  gridTemplateRows = '';
  // local variable to show/hide autogenerated rows in grid layout
  // - this is how grid layout is used to preview only pre-defined number of rows
  //   without knowing/limiting the number of elements in the grid
  hideAutogeneratedRows = this.showOnlyInitialRows;

  swiperConfig: SwiperOptions = {
    slidesPerView: 6,
    spaceBetween: 22.36,
    slidesOffsetAfter: 8,
    navigation: {
      nextEl: `.games-swiper-navigation-right-providers`,
      prevEl: `.games-swiper-navigation-left-providers`,
      enabled: true,
    },
    scrollbar: { draggable: true },
  };

  constructor(
    private breakpointObserver: BreakpointObserver,
    private gamesService: GamesService,
    private assetsService: AssetsService,
    private gameCategoryService: GameCategoriesService,
    private router: Router,
    private cdr: ChangeDetectorRef,
    private route: ActivatedRoute
  ) {
    this.breakpointObserver.observe(AppBreakpoints.LtSmall2).subscribe((value) => {
      this.swiperConfig.slidesPerView = value.matches ? 'auto' : 6;
      this.swiperConfig.spaceBetween = value.matches ? 7.5 : 22.36;

      this.swiperConfig = { ...this.swiperConfig };
    });
  }

  get isLive() {
    return this.route.snapshot.data?.['isLive'];
  }

  ngOnInit() {
    this.gridTemplateRows = `repeat(${this.initialRows}, 1fr)`;
    // check if initialRows is auto
    if (!this.initialRows) {
      this.hideAutogeneratedRows = false;
    }

    this.loadProviders();
  }

  onImgError(event: any) {
    if (!event.target) return;

    if (!event.target.alreadySet) {
      event.target.src = this.missingImgUrl;
      event.target.alreadySet = true;
    }
  }

  private loadProviders() {
    // Load providers

    this.gameCategoryService.gameCategories$
      .pipe(
        switchMap((gameCategoryIds) => {
          return this.gamesService.getAllProviders(
            this.router.url.includes('/games-live')
              ? gameCategoryIds[ProvidersLobbyEnum['Lobby live']]?.toString()
              : gameCategoryIds[ProvidersLobbyEnum.Lobby]?.toString()
          );
        })
      )
      .subscribe({
        next: (data) => {
          this.providersList = [...data];
          this.allProvidersCount = this.providersList?.length ?? 0;
          this.cdr.detectChanges();
        },
      });
  }
}
