import { CdnizePipe } from '@app/@pipes/cdnize.pipe';
import { PaymentMethod } from '@app/@shared/models';

export const DepositMethods: PaymentMethod[] = [
  {
    name: 'Visa',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Visa_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Maestro',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Maestro_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Mastercard',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/MasterCard_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Interac',
    type: 'Bank Transfer',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Interac_Colored.svg',
    currencyCode: '€',
  },
  {
    name: 'Skrill',
    type: 'E-Wallet',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/skrill_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Neteller',
    type: 'E-Wallet',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Neteller_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Paysafe card',
    type: 'Voucher',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Paysafe_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Bitcoin',
    type: 'Bitcoin',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.0001,
    max: 0.4,
    imgAssetPath: 'assets/general/payments/BitCoin_payment.svg',
    currencyCode: 'BTC',
  },
  {
    name: 'Ethereum',
    type: 'Ethereum',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.01,
    max: 5.92,
    imgAssetPath: 'assets/general/payments/ethereum_payment.svg',
    currencyCode: 'ETH',
  },
  {
    name: 'Litecoin',
    type: 'Litecoin',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.01,
    max: 60,
    imgAssetPath: 'assets/general/payments/LiteCoin_payment.svg',
    currencyCode: 'LTC',
  },
  {
    name: 'Tether',
    type: 'Tether',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Tether_payment.svg',
    currencyCode: 'USDT',
  },
];

export const WithdrawMethods: PaymentMethod[] = [
  {
    name: 'Visa',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Visa_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Maestro',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Maestro_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Mastercard',
    type: 'Credit Card',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/MasterCard_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Interac',
    type: 'Bank Transfer',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Interac_Colored.svg',
    currencyCode: '€',
  },
  {
    name: 'Skrill',
    type: 'E-Wallet',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/skrill_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Neteller',
    type: 'E-Wallet',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Neteller_payment.svg',
    currencyCode: '€',
  },
  {
    name: 'Bitcoin',
    type: 'Bitcoin',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.0002,
    max: 0.4,
    imgAssetPath: 'assets/general/payments/BitCoin_payment.svg',
    currencyCode: 'BTC',
  },
  {
    name: 'Ethereum',
    type: 'Ethereum',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.01,
    max: 5.92,
    imgAssetPath: 'assets/general/payments/ethereum_payment.svg',
    currencyCode: 'ETH',
  },
  {
    name: 'Litecoin',
    type: 'Litecoin',
    fee: 'Free',
    processingTime: 'Instant',
    min: 0.3,
    max: 60,
    imgAssetPath: 'assets/general/payments/LiteCoin_payment.svg',
    currencyCode: 'LTC',
  },
  {
    name: 'Tether',
    type: 'Tether',
    fee: 'Free',
    processingTime: 'Instant',
    min: 10,
    max: 10000,
    imgAssetPath: 'assets/general/payments/Tether_payment.svg',
    currencyCode: 'USDT',
  },
  {
    name: 'Bank transfer',
    type: 'Bank Transfer',
    fee: '3.75% fee and 5 EUR fixed *',
    processingTime: '3-5 days',
    min: 400,
    max: 6000,
    imgAssetPath: 'assets/general/payments/BankTransfer_payment.svg',
    currencyCode: 'NZD',
  },
];
