import { SportsbookBetHistoryModelResolved } from '@app/@shared/models/sportsbook.model';

export const SportsbookHistoryMockData: SportsbookBetHistoryModelResolved[] = [
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Laughing Buddah: Hold & Win ',
    winAmount: 1,
    generalStake: 0.2,
    betSlipId: 1,
    externalBetSlipId: 'ALE-ca696727-d9c2-3b36-821d-23ac2a35c4d6',
    locale: 'pt-BR',
    settleTime: new Date().toISOString(),
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test2',
    winAmount: 6.2,
    generalStake: 0.5,
    betSlipId: 2,
    externalBetSlipId: 'ALE-ca696727-d9c2-3b36-821d-23ac2a35c4d6',
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test3',
    winAmount: 3,
    generalStake: 0.8,
    betSlipId: 3,
    externalBetSlipId: 'ALE-ca696727-d9c2-3b36-821d-23ac2a35c4d6',
    settleTime: new Date().toISOString(),
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test3',
    winAmount: 3,
    generalStake: 0.8,
    betSlipId: 4,
    externalBetSlipId: 'ALE-ca696727-d9c2-3b36-821d-23ac2a35c4d6',
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Laughing Buddah: Hold & Win ',
    winAmount: 1,
    generalStake: 0.2,
    betSlipId: 5,
    externalBetSlipId: 'ALE-ca696727-d9c2-3b36-821d-23ac2a35c4d6',
    settleTime: new Date().toISOString(),
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test2',
    winAmount: 6.3,
    generalStake: 0.5,
    betSlipId: 6,
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test3',
    winAmount: 3,
    generalStake: 0.8,
    betSlipId: 7,
  },
  {
    insertDate: new Date().toISOString(),
    betSlipDescription: 'Test3',
    winAmount: 3,
    generalStake: 0.8,
    betSlipId: 8,
  },
];
